### ISSUE TITLE
segfault on linux if X display is not available

### ISSUE THREAD

**Issue by jfirebaugh** [stackgl/headless-gl#10]
I tried to use headless-gl on Travis [without xvfb running](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)), and it segfaulted the node process. Instead it should throw an error with a useful diagnostic message.

Once I added the standard xvfb incantation to .travis.yml it worked.

**Comment by mikolalysenko** [comment]
Should be fixed in gl@2.0.0, but need to test on linux to confirm.
