### ISSUE TITLE
Restore Travis builds

### ISSUE THREAD

**Issue by mourner** [stackgl/headless-gl#100]
@mikolalysenko I see that the travis build was disabled at some point, although the config is still in the repo — do you remember why? Can we reenable it?

**Comment by mikolalysenko** [comment]
I'm not sure what happened and it has been long enough that I can't remember why it is disabled.  It should probably be turned back on.

**Comment by mourner** [comment]
@mikolalysenko looks like Travis is enabled and running fine, it's just that the GitHub hook is not there for some reason. Should a minute to add back.
