### ISSUE TITLE
three.js smoothing breaks with normal maps, rendering with headless-gl

### ISSUE THREAD

**Issue by birdstare** [stackgl/headless-gl#107]
Attempting to render a three.js scene with headless-gl. Works as expected until I add a normal map to MeshPhongMaterial. This appears to break three.js's smooth shading.
  
Render with headless-gl before adding normal map:
![output1](https://cloud.githubusercontent.com/assets/10536484/24730209/1fe1e428-1a17-11e7-8272-2f5aa0caedda.png)

Render with headless-gl with normal map:
![output2](https://cloud.githubusercontent.com/assets/10536484/24730217/2fa07050-1a17-11e7-9f13-fd52b76f8455.png)

**Comment by Samsy** [comment]
Any news on this one ? :)

**Comment by nmck** [comment]
I just came across this issue too, any news on it?

**Comment by dhritzkiv** [comment]
This *may* be address in the standard derivatives extension release (v4.5.0)
