### ISSUE TITLE
zero-arg createContext fails on linux

### ISSUE THREAD

**Issue by jfirebaugh** [stackgl/headless-gl#11]
On linux, `require('gl').createContext()` ([as shown in the README](https://github.com/mikolalysenko/headless-gl#multiple-contexts)) produces the following error:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  18
  Current serial number in output stream:  22
```

If a no-argument call is not intended to work (it does work on OS X), the README should show the intended usage and createContext should check the arguments.

**Comment by mikolalysenko** [comment]
Fixed in gl@2.0.0
