### ISSUE TITLE
uniform/vertex *v methods should accept vanilla JS arrays

### ISSUE THREAD

**Issue by jfirebaugh** [stackgl/headless-gl#12]
The `uniform[1234][fi]v`, `uniformMatrix[234]fv`, and `vertexAttrib[1234]fv` methods should accept a vanilla JavaScript array as the values argument. Currently they work only when passed `Float32Array`/`Int32Array` and segfault when passed a regular array.

**Comment by mourner** [comment]
> Currently I am waiting until the new ABI in node 0.12 stabilizes before jumping in and making a bunch of changes here.

@mikolalysenko Node 0.12 is there, any updates on your plans here? :)

**Comment by mikolalysenko** [comment]
@mourner hmm probably a good time to reevaluate this project.  It basically needs a complete rewrite at this point.  Fortunately I did manage to get some good progress on porting the WebGL conformance suite to node:

https://github.com/stackgl/gl-conformance

If some one else wants to take over the project, I'd be happy passing on the torch, or alternatively if everyone is willing to wait until I get done with my current projects I could maybe help out starting some time in May.

**Comment by mikolalysenko** [comment]
Fixed by https://github.com/stackgl/headless-gl/commit/6a32cfb66f7f9fef8188b3d06a021ab52e47b1f4
