### ISSUE TITLE
Build fails on node 9.2 in Windows 10 x64 

### ISSUE THREAD

**Issue by misterfresh** [stackgl/headless-gl#127]
In Windows I get the error Link Incremental not compatible with Opt No Ref. Not sure how to disable incremental linking. I edited bindings.gyp to remove the line with the Link Incremental setting, or to set it to 1, but it made no difference.

**Comment by misterfresh** [comment]
It does work in ubuntu though.

**Comment by zohar1000** [comment]
hi @misterfresh , did you manage to find a solution for that? I'm having the same problem now and I cannot bypass it.

**Comment by jeanbmar** [comment]
Same issue, could be similar to https://github.com/PCSX2/pcsx2/issues/1288 ?

**Comment by artemzakharov** [comment]
@jeanbmar where is the bindings.gyp file you edited?

**Comment by jeanbmar** [comment]
Ah sorry i meant binding<del>**s**</del>.gyp:
https://github.com/stackgl/headless-gl/blob/master/binding.gyp
