### ISSUE TITLE
Syntax error for precision

### ISSUE THREAD

**Issue by petitssoldats** [stackgl/headless-gl#13]
Hi, i try to adapt the three.js library to your ambitious project (really really cool).
I don't know if the adaptation is possible, but it could offer a precious help for the webgl community for the Three.js scene server side rendering.
After fixing variables and headless stuff issues, i got an error during the shader compilation which look like to :
``` 'precision' : syntax error: syntax error ```

Do you have an idea about that ?
I searched by my side, but i found nothing :disappointed:

Thans for all :bowtie:

**Comment by ppalludan** [comment]
@petitssoldats any progress on this three.js serverside rendering, any way I can contribute ?

**Comment by petitssoldats** [comment]
hé @ppalludan,

I fixed the problem of ```precision``` but after that i had a lot of issue about compatibilities.
So, i'm taking a look at nw.js or atom-shell for a server side rendering on a non headless server :+1:

**Comment by mikolalysenko** [comment]
Fixed in gl@2.0.0
