### ISSUE TITLE
Release 4.1.1 to npm

### ISSUE THREAD

**Issue by dhritzkiv** [stackgl/headless-gl#136]
Even though I have repo access, I do not appear to have npm access, and therefore cannot push 4.1.1 to npm.

4.1.1 includes:

- OES_element_index_uint extension support (#121)
- OES_texture_float extension support (#135)
- Support Image, Video elements when Canvas elements not available (#87)
- Misc. fixes (license and readme fixes in package.json, install instructions in README)

4.1.1 will also require new precompiled binaries. Ideally, these would be generated and uploaded as part of CI, but I believe uploading is currently broken due to outdated credentials (which I don't have the permissions to upload from Travis to GitHub)

**Comment by mourner** [comment]
@dhritzkiv just added you as an owner in NPM — thanks for flagging!

Also, great to see movement on the CI front — I tried to figure out how to re-enable Travis at some point, but got tangled and gave up. Now if only we could fix the intermittent AppVeyor failures...

**Comment by dhritzkiv** [comment]
@mourner Thanks! I'll publish to npm once I upload some prebuilt binaries built into the Github release.

And yeah, absolutely no idea what is going on with AppVeyor /Windows

**Comment by mourner** [comment]
@dhritzkiv perhaps worth disabling AppVeyor until we figure it out?

**Comment by dhritzkiv** [comment]
Could be handy so we don't get false negatives during PRs and general pushes. Okay. I'll disable it in the meantime.

**Comment by dhritzkiv** [comment]
Released!
