### ISSUE TITLE
binaries for 4.1.1 release?

### ISSUE THREAD

**Issue by alecf** [stackgl/headless-gl#138]
similar to #134, when we build 4.1.1, we're no longer getting binaries. Any chance for new binaries (including for node 10)

**Comment by dhritzkiv** [comment]
Hi @alecf. The binaries should be there. Check the releases page. I just managed to install gl via npm without requiring a compilation.

**Comment by alecf** [comment]
They dont' seem to be working, I see this in my build:

```
> gl@4.1.1 install /code/node_modules/gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /code/node_modules/gl/build/Release/webgl.node)
make: Entering directory '/code/node_modules/gl/build'
  CXX(target) Release/obj.target/angle_common/angle/src/common/Float16ToFloat32.o
  CXX(target) Release/obj.target/angle_common/angle/src/common/MemoryBuffer.o
  CXX(target) Release/obj.target/angle_common/angle/src/common/angleutils.o
```

**Comment by dhritzkiv** [comment]
It seems the rebuilt binaries were built with a newer version of gcc which introduces a new cpp ABI as a requirement.  Any chance you could update `libstdc++` on your machine to something recent?

**Comment by alecf** [comment]
That seems to be it! For folks following along this meant moving from `node:10.12.0` docker images to `node:10.12.0-stretch`

thanks!
