### ISSUE TITLE
issue with for loop with float ending early

### ISSUE THREAD

**Issue by robertleeplummerjr** [stackgl/headless-gl#140]
If I use a float constant in a for loop for the upper bound of the loop, the loop ends early.  The exact source to reproduce the specific issue:

```glsl
const float constants_width = 6.0;
  float customFn() {
    float user_sum = 0.0;
    // bug starts here
    for (float user_i = 0.0; user_i < constants_width; user_i++) { // constants_width is 6, but user_sum only counts to 2.  
    // bug ends here
      user_sum++;
    }
    return user_sum;
}
```

What I've found:
* `float1 < float2` reproduces the problem
* `float1 <= float2` works as expected
* `int1 <= int2` works as expected
* `int1 <= int2` works as expected

Google Angle translates the GLSL that it is input from webgl glsl to opengl glsl, this is where I thought the bug was at first, but have found that doesn't seem to be the case.  The original webgl glsl, translated opengl glsl, and steps to reproduce (at least on my osx mac in node) can be found here: https://gist.github.com/robertleeplummerjr/aa0a8bb9250426e5a3e9e360482b3083

I've been investigating this issue, and will continue to do so.  After considerable research, recompiling google angle, tracing debugs, I've uncovered that the bug seems to be in https://www.khronos.org/opengles/  via:

* https://github.com/mikolalysenko/angle/blob/9216e68641b39b6509ef8358d8b022f87d74338b/include/GLES2/gl2.h#L544
* Which imports: `#include <GLES2/gl2platform.h>` [here](https://github.com/mikolalysenko/angle/blob/9216e68641b39b6509ef8358d8b022f87d74338b/include/GLES2/gl2.h#L39)
* Which tells us that this version is from `$Revision: 23298 $ on $Date: 2013-09-30 17:07:13 -0700 (Mon, 30 Sep 2013) $` [here](https://github.com/mikolalysenko/angle/blob/9216e68641b39b6509ef8358d8b022f87d74338b/include/KHR/khrplatform.h#L29)

I believe there are two paths that can be followed here: either upgrade OpenGL ES, or upgrade Google Angle

Still investigating.

**Comment by robertleeplummerjr** [comment]
Notice, this stuff is new to me, so I apologize if my terminology isn't correct.

**Comment by dhritzkiv** [comment]
I haven't fully read this PR yet, but as to your point about GLES: I believe your system's installation is preferred. macOS' implementation hasn't been updated in 5 years (2013) and is now deprecated, and no updates are expected. So the issue cannot be fixed there.

**Comment by robertleeplummerjr** [comment]
I talked with the OpenGL guys on freednode and they mentioned a few things I can try, but more specifically they said that counting in this way was not really intended with floats, and that it'd be more appropriate to use integers.  I was assured that the fears I have about using the index as an integer in the code, casting when needed to float, should likely be a near zero cost and it is more just a requirement of good programming.  I'm going to try that soon, but first I'm going to upgrade angle, and see what that befits me.

**Comment by robertleeplummerjr** [comment]
I just did a make-shift shanty upgrade of google angle, and to my unapproximated glee, ran `node test.js` to reproduce the issue, and found a `console.log` output of:

```
Float32Array [ 6, 6, 6, 6, 6, 6 ]
```

Rather than the 

```
Float32Array [ 2, 2, 2, 2, 2, 2 ]
```

Which I had been getting.  In other words, upgrading google angle resolves this issue. I'll see what I can do to upgrade the build system.

**Comment by robertleeplummerjr** [comment]
Though not yet at all ready for release, I've updated the build file in my local, in case anyone was interested: https://github.com/robertleeplummerjr/headless-gl/commit/4bf68ae3422c68bd272b90767d664e91ac67ea53

I'll be adding more later this week.

**Comment by robertleeplummerjr** [comment]
I ended up fixing this in GPU.js by iterating in loops using integers.  It took a quite large overhaul, but it was the right one.  There is a bug in Google Angle, however, to anyone reading this, at least of the version currently assigned to work with headless-gl.  If you run into it, likely it is because you are on a mac, and rather than start diving into the large pipeline that is Google Angle, to find out what is wrong, simply iterate using integers.

Easy peasy.
