### ISSUE TITLE
support for WEBGL_draw_buffers?

### ISSUE THREAD

**Issue by robertleeplummerjr** [stackgl/headless-gl#142]
How hard would it be to get the https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_draw_buffers extension working?

**Comment by dhritzkiv** [comment]
Without peeking into this, it should be possible by: checking if the extension is in the `getSupportedExtensions` list and returning a truthy value; by defining the relevant constants; and by handling any special cases in the draw calls.

Tests might be a different problem as they may or may not pass, even if the implementation is sound. Though, likely the current conformance suite should handle it.

**Comment by robertleeplummerjr** [comment]
I've checked on my newer build of angle with headless-gl, and the extension is there, seemingly by default.  So I'm adding the bindings for it.

**Comment by robertleeplummerjr** [comment]
This is essentially my patch, but it isn't outputting anything to the textures, so opening an issue with Google Angle: https://gist.github.com/robertleeplummerjr/cce00202e08954cf8df512eed838de66
