### ISSUE TITLE
texImage2D function is not supported here.

### ISSUE THREAD

**Issue by Divy123** [stackgl/headless-gl#143]
I guess the function texImage2D is not supported here

**Comment by jywarren** [comment]
Hi @Divy123 it looks like some people are using it! https://github.com/stackgl/headless-gl/search?q=texImage2D&type=Issues

https://github.com/stackgl/headless-gl/pull/20

https://github.com/stackgl/headless-gl/pull/53/files#diff-c24e210c8552e30550810a8b75aa1cdaR101

@tech4GT take a look here too!

**Comment by dhritzkiv** [comment]
Closing in favour of #149
