### ISSUE TITLE
gl.getParameter(gl.MAX_DRAW_BUFFERS_WEBGL)

### ISSUE THREAD

**Issue by Somebi** [stackgl/headless-gl#153]
Returns null
`gl.MAX_DRAW_BUFFERS_WEBGL` is undefined
The only way to know max possible draw buffers is to iterate over available constants COLOR_ATTACHMENT${i}_WEBGL until reach undefined.

**Comment by Somebi** [comment]
> The maximum size of the array passed to drawBuffersWEBGL depends on the system and can be queried by calling gl.getParameter(gl.MAX_DRAW_BUFFERS_WEBGL). In GLSL, this is also available as gl_MaxDrawBuffers.

**Comment by robertleeplummerjr** [comment]
This is resolved with: `gl.getParameter(gl.getExtension('WEBGL_draw_buffers').MAX_DRAW_BUFFERS_WEBGL)`

In webgl1 this comes from the extension.
