### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wdl000001** [stackgl/headless-gl#155]

**Comment by wdl000001** [comment]
`PS G:\gpu.js-develop> npm i gl

> gl@4.2.2 install G:\gpu.js-develop\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 libc= platform=win32)

G:\gpu.js-develop\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\gpu.js-develop\node_modules\gl
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WL\AppData\Roaming\npm-cache\_logs\2019-04-30T16_23_30_217Z-debug.log`

**Comment by dhritzkiv** [comment]
I believe the issue stems from this command run by node-gyp:

```cmd
C:\Program Files\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
```

I suspect the `-c` argument needs to be wrapped in quotes, but isn't.

A quick perusal of node-gyp issues suggest that [python3 isn't supported, and that using 2.7 is recommended.](https://github.com/nodejs/node-gyp/issues/1683) Other issues suggest using Powershell vs. command prompt.

Unfortunately, I'm not well versed in Windows development intricacies, so I'm not able to help much.

I will close this issue as it is not strictly related to headless-gl, but to node-gyp. Please re-open if you think this is not the case, and also please post your eventual solution.
