### ISSUE TITLE
Differences between frontend and backend rendering

### ISSUE THREAD

**Issue by kbruneel** [stackgl/headless-gl#158]
Hi,

I'm trying headless-gl with three.js. It's important to me that the images that are rendered in the frontend are (almost) equal to the ones rendered in the backend.

This is the code I use to setup the three.js renderer for both cases:
```javascript
if (isFrontend) {
    renderer = new THREE.WebGLRenderer();
} else {
     var gl = require('gl');
     renderer = new THREE.WebGLRenderer({
         canvas: {
             addEventListener: function(){}
         },
         context: gl(width, height)
    });
}
```

All other code is the same, but I still get large differences in the the rendered image (same machine). It looks like the the headless-gl version is zoomed out or the camera is further away (I checked the camera position and they are the same).

I think, I don't use unsupported features. The scene is just a few simple meshes using THREE.MeshBasicMaterial.

Is this a bug, or Is it normal to get these kind of differences? Am I too demanding to expect the same result?

What could I do to eliminate the differences?

Thanks a lot!
Karel

**Comment by dhritzkiv** [comment]
I’ve used shared code between the front and backend and I haven’t had any differences between the FOV or other camera properties.

Note: you may find slight differences in anti-aliasing, but otherwise it should be consistent.

One thing to check is that the canvas dimensions are the same in both cases.

**Comment by dhritzkiv** [comment]
Other rendering differences (transparencies, shadows, normals) may require certain extensions to be enabled

**Comment by kbruneel** [comment]
I get the following messages in the console:
THREE.WebGLRenderer 104
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
THREE.WebGLRenderer: OES_standard_derivatives extension not supported.
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

Could this have anything to do with it?

I don't think it's anti-aliasing since  the differences are multiple pixels wide, but I'm certainly not an expert.

In both cases I use 
``` javascript
renderer.setSize(width, height, false);
```
to set the size. How can I check the canvas size?

**Comment by kbruneel** [comment]
@dhritzkiv Do you have any comment on ^^^?

Thanks!

**Comment by dhritzkiv** [comment]
Those extensions shouldn't have an effect on the rendering issues you're describing.

I would recommend trying to create the basic scene from three.js for both frontend and backend. And feel free to post screenshots of the issue.

**Comment by kbruneel** [comment]
I found my problem. It was in the svg parser I used to generate the mesh. So this has nothing to do with headless-gl. All works fine now.

Sorry for the diversion.

**Comment by neuro-sys** [comment]
@dhritzkiv 

> Other rendering differences (transparencies, shadows, normals) may require certain extensions to be enabled

I have a difference only in alpha channel, and I'm getting the same warnings about extensions, any clues on this?

Frontend:
![image](https://user-images.githubusercontent.com/648622/133257517-36c90e09-0218-4ad8-b36d-ba2693f11865.png)

Backend:
![image](https://user-images.githubusercontent.com/648622/133257611-6b586392-26f8-44da-819a-f2f904bb0389.png)
