### ISSUE TITLE
Headless-GL on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by mavrovgeorgi** [stackgl/headless-gl#162]
Hello,

I have a problem install it on an ubuntu server.
I cloned and installed it, following the instructions.
When I go into the cloned folder and I try to test it with "npm test" I receive the follow error.

`
> gl@4.3.3 test /root/headless-gl
> standard | snazzy && tape test/*.js | faucet

/root/headless-gl/test/blending.js:19
    equn: gl.FUNC_ADD,
             ^

TypeError: Cannot read property 'FUNC_ADD' of null
    at Object.<anonymous> (/root/headless-gl/test/blending.js:19:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /root/headless-gl/node_modules/tape/bin/tape:39:9
    at Array.forEach (<anonymous>)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
npm ERR! Test failed.  See above for more details.

`

I would be very thankful to any suggestions!

Have a nice day!

**Comment by dhritzkiv** [comment]
Hi @mavrovgeorgi.

It looks like `gl` is undefined, which suggests that a part is missing. Did you install the system dependencies for linux as described [here](https://github.com/stackgl/headless-gl#ubuntudebian)? Note: some of these packages and names may vary between versions of distributions.

Another thing to try is to [build it from scratch](https://github.com/stackgl/headless-gl#how-should-i-set-up-a-development-environment-for-headless-gl) (running `npm install` likely used a pre-built version):

0. Make sure you have the dependencies as specified above
1. `git clone` this repo, then `cd` into it
1. `git submodule init`
1. `git submodule update`
1. `npm install`
1. `npm run rebuild`

Then try running `npm test`

**Comment by mavrovgeorgi** [comment]
Hi @dhritzkiv.

Thank you for your response.
I checked the system dependencies for linux. 

Actually the **gl** could not be installed, probably because I am trying to install it on a headless server(without GPU)..
So I could not check for "Working and up to date OpenGL drivers"  

I tried the "build from scratch" as well at the beginning.

Do you have any suggestions how could I fix the gl?

Thank you!

**Comment by dhritzkiv** [comment]
headless-gl is meant to be installed on a headless server, including those without GPUs!

Could you try one more thing? Instead of running `npm install`, could you run:

```sh
xvfb-run --auto-servernum --server-num=1 -s "-ac -screen 0 1280x1024x24" `which glxinfo`
xvfb-run --auto-servernum --server-num=1 -s "-ac -screen 0 1280x1024x24" `which npm` test
```

This is necessary because you need to start a virtual frame buffer in order to have a drawing surface.

**Comment by mavrovgeorgi** [comment]
Yes, I tried both commands. Now we have a progress.
Running the first one, there is much information about the version etc.

After running the second one, there is some progress and I receive another error:

`gl@4.3.3 test /root/headless-gl
> standard | snazzy && tape test/*.js | faucet

✓ alpha texture
# attribs_gl-bindAttribLocation-aliasing
  ok 3 Vertex shader compiled successfully.LLVM ERROR: out of memory
✓ attribs_gl-bindAttribLocation-aliasing
not ok 4 no plan found
⨯ fail  1
npm ERR! Test failed.  See above for more details.`

**Comment by dhritzkiv** [comment]
"out of memory" suggests that your machine may be out of memory. Is that a possibility?

Could you try running the test command above, but swap out `1280x1024x24` with something smaller like `320x320x24`?

Sorry that this is happening - I've never seen this before!

---

By the way, when you're pasting in a block of code, use three ticks, like this: \`\`\`. You only used one, but I edited your comment for you

**Comment by robertleeplummerjr** [comment]
I'm running into the same issue, but I have a massive server gifted from LeaderGPU for open source.  @dhritzkiv, I can get you shell access, would you mind looking?

**Comment by robertleeplummerjr** [comment]
I think this is a driver issue for me, seems like opengl, although I've selected nvidia drivers to be installed on server start, had not been included.  But still digging.

**Comment by robertleeplummerjr** [comment]
I got unit test running.  This did the trick for me:
```
sudo ubuntu-drivers autoinstall
```

**Comment by dhritzkiv** [comment]
@robertleeplummerjr Thanks for getting that server set up and for figuring it out. Sorry I wasn't able (and won't be able to for some time) to help out.

In any case, I wonder why `LLVM ERROR: out of memory` was happening for a driver issue…

**Comment by robertleeplummerjr** [comment]
Because my issue was identical, and the fix is posted, going to go ahead and close.  Let us know if you have any more issues.

**Comment by srameshr** [comment]
@robertleeplummerjr @dhritzkiv I still see this issue.
Using ```xvfb-run -s '-screen 0 1024x768x24 -ac +extension GLX +render -noreset' node index.js``` fails with an out of memory error if FFMPEG is encoding video which is 720P in width.

**Comment by dhritzkiv** [comment]
@srameshr what are your system details (OS, RAM, CPU)? Also, where does FFMPEG come into play?
