### ISSUE TITLE
gl ways returns null

### ISSUE THREAD

**Issue by alexeightsix** [stackgl/headless-gl#163]
I had issues getting this setup within a docker container but ended up running:

RUN apt-get -y --force-yes install x-window-system
RUN apt-get install -y mesa-utils

and it worked

**Comment by alexeightsix** [comment]
@stijnb1234 

The docker run command executed this script, not the best way but that's what we came up with and seems to have worked ever since:

```
#!/usr/bin/env sh
sh xvfb_init start

#Wait till Xvfb is started
until pids=$(pidof Xvfb)
do   
	sleep 10
	sh xvfb_init start
done

npm rebuild sharp && npm rebuild gl && npm run watch
```

**Comment by stijnb1234** [comment]
> @stijnb1234
> 
> The docker run command executes this script, not the best way but that's what we came up with and seems to have worked ever since:
> 
> ```
> #!/usr/bin/env sh
> sh xvfb_init start
> 
> #Wait till Xvfb is started
> until pids=$(pidof Xvfb)
> do   
> 	sleep 10
> 	sh xvfb_init start
> done
> 
> npm rebuild sharp && npm rebuild gl && npm run watch
> ```
> 
> Edit: I'm not sure if that loop above is related to the original question as it's been awhile .. but I think this is what perm fixed it.

Thanks! I had to start xvfb by hand (using the command you provided in your script), which fixed the issue.
