### ISSUE TITLE
Modernization of lib?

### ISSUE THREAD

**Issue by robertleeplummerjr** [stackgl/headless-gl#166]
I'm curious what thoughts are on moving constructors into their own files, as classes, some cleanup, and adding semicolons?

**Comment by robertleeplummerjr** [comment]
My IDE (WebStorm) goes into HIGH cpu mode when I open the lib because of no semicolons, is why I bring it up.

**Comment by dhritzkiv** [comment]
lol sounds like a bad IDE…

**Comment by dhritzkiv** [comment]
But yes, the library could use some modernization in terms of cleaning up into classes, separate files, etc. and adding better style formatting + linting.

**Comment by robertleeplummerjr** [comment]
Behold!  Classes! - https://github.com/stackgl/headless-gl/commit/f5139a2b9164cf9db19f0631fe56aa62d25fb375

**Comment by dhritzkiv** [comment]
Noice. Thanks for cleaning up the directories/structure of the project, too

**Comment by robertleeplummerjr** [comment]
I've got most of the library working fine, but for some reason when I get to the test where it is failing in travis I've narrowed it down to the `context.destroy()` which calls the `super.destroy()` works the first time, but the second call causes node to throw a pretty ambiguous exception: `Abort trap: 6`, any clues?

**Comment by dhritzkiv** [comment]
No. Some cursory searching for the term suggests we're writing to memory we don't own? I'm not sure how that's possible.

Could be a Travis issue

**Comment by robertleeplummerjr** [comment]
I miss-read the travis failure, it is legit, however the issue I was seeing, though near that failing unit test, actually seems to come from this line:
```js
        assertOk("x < 0 full width", function() {
            gl.copyTexSubImage2D(gl.TEXTURE_2D, 0, 0, 0, -1, 0, 16, 16);
        });
```
Later, when the context is being disposed, it throws the `Abort trap: 6` in c++, and causes node to die.  I believe this is actually an OS or driver issue.  Similar bug in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1176404.  Oh well.  Commented it out, and progressing through other meaningful broken parts, will have them fixed as time allots.

**Comment by robertleeplummerjr** [comment]
Pushed some changes that fixed nearly all unit test breaks.  Maybe tomorrow or Tuesday we'll be near or at a pull request. Just fyi.

**Comment by robertleeplummerjr** [comment]
PR opened https://github.com/stackgl/headless-gl/pull/168
