### ISSUE TITLE
Headless Rendering with Xvfb returning Transparent Image

### ISSUE THREAD

**Issue by asaltiel72** [stackgl/headless-gl#167]
I have a problem reading from the canvas and outputting it to an image.
I successfully can run the application on a machine with a display and it works great. 

I created an EC2 instance with Ubuntu 18.04 and installed all my required libs and all the libs listed in the system dependency list and all I need for xvfb to work as outlined. I run my script with xvfb-run as described and it runs successfully but the image returned is transparent.

Any ideas?

**Comment by asaltiel72** [comment]
Update: I have confirmed that my objects are in my scene but the readPixels on my gl context is ALWAYS returning a transparent pixel map. Even if I set the transparent color to red and then immediately read the pixels.

Any help would be appriciated, I've been stuck on this issue for too long

**Comment by robertleeplummerjr** [comment]
Can you give reproduction code?

**Comment by asaltiel72** [comment]
Update: so it finally worked.
I had 2 issues:
1) my gl height and width was too large
2) my application couldn't read from the X display unless it was run with sudo

I initially tried the shrinking the first and it did nothing. Sorry I didn't provide more details for the help.
