### ISSUE TITLE
Extension query for 'OES_standard_derivatives'

### ISSUE THREAD

**Issue by 1chandu** [stackgl/headless-gl#169]
`gl.getExtension('OES_standard_derivatives')` returns false, but using this extension derivative in shader has no errors. 

I see @dhritzkiv commented in #5 in Sept, 2018. Is this still an issue, why `getExtension` returns false?

**Comment by dhritzkiv** [comment]
I believe work to fully support OES_standard_derivatives was started in #72, but was never completed.

It's unclear how much work is required for it to be fully implemented and passing of tests.
