### ISSUE TITLE
Excessive gl.getParameter() calls in gl.drawArrays()

### ISSUE THREAD

**Issue by robertleeplummerjr** [stackgl/headless-gl#178]
Profiling showed this, I tinkered with getting a solution already in place that only checks for this value when absolutely needed.  It wasn't very costly, but was causing a bunch of unneeded calls into the c++ logic, and into google angle.

**Comment by robertleeplummerjr** [comment]
Will this be released soon?

**Comment by dhritzkiv** [comment]
Sorry! Thanks for the reminder. It's out as [v4.4.1](https://github.com/stackgl/headless-gl/releases/tag/v4.4.1)

**Comment by robertleeplummerjr** [comment]
Np!  Ty for your hard work.
