### ISSUE TITLE
Problems running on Digital Ocean droplet

### ISSUE THREAD

**Issue by galipmedia** [stackgl/headless-gl#186]
Hi I am trying to run this using the instructions provided, I have got passed the no context problem by using xvfb but i am getting an error 
```terminate called after throwing an instance of 'std::bad_alloc'```
From what i have read this seems like a memory issue, but i have 16GB. Does anyone know what I can do?

**Comment by dhritzkiv** [comment]
Could you tell us a couple of things to help us out?

- flavour and version of Linux
- node version

Can you also copy + paste the full output of the program when running it?

**Comment by galipmedia** [comment]
Ubuntu 4.15.0-88-generic
Node 10.19.0 (I upgraded from 8.19 which also wasn't working / haven't tried 12)
The exact error is 
``` terminate called after throwing an instance of 'std:bad_alloc'
what(): std_bad_alloc
Aborted (core dumped)
```
My command is
 ```
xvfb-run -s "-ac -screen 0 1920x1080x24" node index.js
```
I am trying to make a transition between different raw images using webgl using the ffmpeg-concat library.

**Comment by galipmedia** [comment]
![image](https://user-images.githubusercontent.com/1904800/75933574-3d1df680-5eca-11ea-9dbe-40c1c31613ad.png)

I get this when i enter ```xvfb-run -s "-screen 0 640x480x24" glxinfo```
Excuse the screenshot, I am using the web based console.

**Comment by galipmedia** [comment]
Not sure if this helps...
![image](https://user-images.githubusercontent.com/1904800/75973428-0de8a300-5f25-11ea-98c4-caa337ab0240.png)

**Comment by galipmedia** [comment]
I solved the problem by completely removing nvidia drivers. Not sure if I installed them at some point or not in my quest to solve this problem, but that was my solution.

**Comment by dhritzkiv** [comment]
Thanks for filling in those details. Someone else may have this issue in the future and this will help them.

Very curious that the Nvidia drivers would cause that. I wonder if there were any updates available for the drivers. Also curious that a headless instance comes with those device drivers
