### ISSUE TITLE
node-pre-gyp binaries

### ISSUE THREAD

**Issue by mourner** [stackgl/headless-gl#19]
2.0.0 requires an extremely long build due to the ANGLE dep (which is bad both for local installs and CI). We need to prebuild the binaries for a few common platforms (Node 0.12 for OS X and Linux in particular) and set them up through https://github.com/mapbox/node-pre-gyp for fast installs.

**Comment by mikolalysenko** [comment]
Agreed.

**Comment by mikolalysenko** [comment]
Currently have binaries for linux and os x 64-bit.  Will work on adding others.  Still need to implement some sort of CI system to automate this on release.

**Comment by mourner** [comment]
Works perfectly, thanks!
