### ISSUE TITLE
How can I contribute to the repository for prebuilt libraries for Node 10.16.x version 

### ISSUE THREAD

**Issue by nikhilso** [stackgl/headless-gl#194]
I use this package for Node 10.x and Node 12.x version of NPM.
Whenever i do npm install on my windows machine it builds the package on my machine.
How can i get the prebuilt package of latest code with Node 10.x and Node 12.x.
Can i contribute or upload the prebuilt package for these node version?
Suggest some solution?

**Comment by dhritzkiv** [comment]
Do you know which architecture your machine is? The latest release (v4.5.2) should have Windows 64bit builds for most of the latest node versions: 8,x, 9.x, 10.x, 11.x, 12.x, 14.x.

We don't currently have 32bit pre-builds as we're lacking the dlls for 32bit openGL.

**Comment by nikhilso** [comment]
I have 64bit node installed, but if i do npm install it asks for building the package from source. How can i avoid that?

**Comment by dhritzkiv** [comment]
Could you post the output of `npm install` up until it starts building from source?

**Comment by nikhilso** [comment]
[gl.zip](https://github.com/stackgl/headless-gl/files/4894949/gl.zip)

Here are the build packages from my machine.

**Comment by dhritzkiv** [comment]
Sorry, I meant the terminal/command prompt output. Copy+paste it in a comment here.

**Comment by nikhilso** [comment]
[build.log](https://github.com/stackgl/headless-gl/files/4902150/build.log)
Here is the build log

**Comment by dhritzkiv** [comment]
Thanks!

Hmm okay. It looks like the prebuilt binary is downloaded, but it's incomplete / incorrectly built by us. Could explain the file size discrepancy (200kiB for Windows, 800kiB for Linux/Darwin).

If you're up to it, could you run http://www.dependencywalker.com/ on the [webgl.node](https://github.com/stackgl/headless-gl/files/4903574/webgl.node.zip) file? (linked for your convenience)

Apologies for the lack of working prebuilt binaries. Us maintainers aren't Windows developers, so we have a hard time debugging these issues

**Comment by nikhilso** [comment]
![image](https://user-images.githubusercontent.com/157522/87165027-2dcf0f80-c2e7-11ea-8b52-91118579b154.png)
This is the image of the dependencies walker

**Comment by dhritzkiv** [comment]
Thanks again.

I suspect we need to bundle the libEGL*.dll files with the prebuild. Which means copying those files to the Release directory, and including the `--include-regex "\.(node|dll)$"` flag.

I'll create a PR soon and create a special npm release.

**Comment by nikhilso** [comment]
Thanks a lot.
I can help you test this prebuilt package, so do let me know once its ready.

**Comment by nikhilso** [comment]
Any update on this issue, i can help to code this change.

**Comment by nikhilso** [comment]
I have shared the Pull Request for the fix can you approve and create new prebuilt package.

**Comment by dhritzkiv** [comment]
Thanks @nikhilso!

It looks like CI has built and pushed the prebuilt binaries. The Windows files are now 3MB (instead of 200kB), which is promising!

Can you try installing the library now? `npm install gl@4.5.3-win64.0`

It's a pre-release, but should install like a regular release.

If that worked, I'll cut a regular release.

**Comment by nikhilso** [comment]
Just used npm command as you mentioned and its working perfectly fine.
You can make the pre-release as regular release.

**Comment by dhritzkiv** [comment]
Done. Release as `4.5.3`
