### ISSUE TITLE
The issue with building  on Windows / Node v12

### ISSUE THREAD

**Issue by ATerentjev** [stackgl/headless-gl#196]
Dear Gurus!
I am working with MapBox-gl some time. Previously, I successfully got a working environment.
But now I started getting an error when preparing development environment. My steps:

clone repository in mapbox-gl-js directory and go in it
npm i node-gyp
I get next log:

`npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm notice created a lockfile as package-lock.json. You should commit this file.

node-gyp@7.0.0
added 99 packages from 66 contributors and audited 101 packages in 12.116s
2 packages are looking for funding
run npm fund for details
found 0 vulnerabilities
PS D:\mapbox\mapbox-gl-js
`
Then when I try
yarn install
I get next log:

PS D:\mapbox\mapbox-gl-js> yarn install

yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by u
nsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning node-gyp > request@2.88.2: request has been deprecated, see request/request#3142
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
warning " > @mapbox/mapbox-gl-rtl-text@0.2.3" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
[5/5] Building fresh packages...
[1/5] ⡀ canvas
[-/5] ⡀ waiting...
[3/5] ⡀ core-js-pure
[4/5] ⡀ gl
error D:\mapbox\mapbox-gl-js\node_modules\gl: Command failed.
Exit code: 7
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: D:\mapbox\mapbox-gl-js\node_modules\gl
Output:
prebuild-install WARN install No prebuilt binaries found (target=12.18.3 runtime=node arch=x64 libc= platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.18.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args 'D:\mapbox\mapbox-gl-js\node_modules\gl\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-G',
gyp info spawn args 'msvs_version=2015',
gyp info spawn args '-I',
gyp info spawn args 'D:\mapbox\mapbox-gl-js\node_modules\gl\build\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'D:\mapbox\mapbox-gl-js\node_modules\gl\node_modules\node-gyp\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\Users\myadmin\.node-gyp\12.18.3\include\node\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\Users\myadmin\.node-gyp\12.18.3',
gyp info spawn args '-Dnode_gyp_dir=D:\mapbox\mapbox-gl-js\node_modules\gl\node_modules\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\Users\myadmin\.node-gyp\12.18.3\<(target_arch)\node.lib',
gyp info spawn args '-Dmodule_root_dir=D:\mapbox\mapbox-gl-js\node_modules\gl',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'D:\mapbox\mapbox-gl-js\node_modules\gl\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build/binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "D:\mapbox\mapbox-gl-js\node_modules\gl\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\mapbox\mapbox-gl-js\node_modules\gl
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v4.0.0

PS D:\mapbox\mapbox-gl-js>
Can't anybody help how to fix issue ?

**Comment by dhritzkiv** [comment]
I think there are two issues:

1. gl@4.3.3 (the version that mapbox-gl-js uses) doesn't have prebuilt binaries for Windows (4.5.3 onward does); because of that:
2. it requires building from source with Visual Studio. Can you confirm that it's available on your system? `spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT` suggests it isn't (but it could mean something else)

Can you try running `npm install`ing `gl@4.3.3` on its own? The error logs might be clearer about what's going wrong.

The solution might be to update mapbox-gl-js's dependency on gl to 4.5.3

**Comment by ATerentjev** [comment]
Thank you very much!!! I'l try.
1. PS D:\mapbox\mapbox-gl-js> npm install ing gl@4.3.3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\rimraf.cmd as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\rimraf
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\rimraf as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\rimraf
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\semver.cmd as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\semver
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\semver as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\semver
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\nopt.cmd as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\nopt
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\nopt as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\nopt
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\mkdirp.cmd as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\mkdirp
npm WARN rm not removing D:\mapbox\mapbox-gl-js\node_modules\.bin\mkdirp as it wasn't installed by D:\mapbox\mapbox-gl-js\node_modules\mkdirp

> gl@4.3.3 install D:\mapbox\mapbox-gl-js\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.1.0 runtime=node arch=x64 libc= platform=win32)

D:\mapbox\mapbox-gl-js\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\nod
gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:413:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\mapbox\mapbox-gl-js\node_modules\gl
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\documentation\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\postcss-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @mapbox/mapbox-gl-rtl-text@0.2.3 requires a peer of mapbox-gl@>=0.32.1 <2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @mapbox/mapbox-gl-supported@1.5.0 requires a peer of mapbox-gl@>=0.32.1 <2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gl@4.3.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the gl@4.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myadmin\AppData\Roaming\npm-cache\_logs\2020-07-25T05_36_15_345Z-debug.log
PS D:\mapbox\mapbox-gl-js>

**Comment by ATerentjev** [comment]
`The solution might be to update mapbox-gl-js's dependency on gl to 4.5.3`
After npm i gl@4.5.3  yarn installed successfully:
`pbox\mapbox-gl-js> npm install gl@4.5.3
 deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

.3 install D:\mapbox\mapbox-gl-js\node_modules\gl
ld-install || node-gyp rebuild

ce created a lockfile as package-lock.json. You should commit this file.
 optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
 notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
 optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\documentation\node_modules\chokidar\node_modules\fsevents):
 notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
 optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\postcss-cli\node_modules\chokidar\node_modules\fsevents):
 notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
 @mapbox/mapbox-gl-rtl-text@0.2.3 requires a peer of mapbox-gl@>=0.32.1 <2.0.0 but none is installed. You must install peer dependencies yourself.
 @mapbox/mapbox-gl-supported@1.5.0 requires a peer of mapbox-gl@>=0.32.1 <2.0.0 but none is installed. You must install peer dependencies yourself.
 ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

.3
 packages from 27 contributors, removed 5 packages and audited 2028 packages in 32.998s
9 vulnerabilities (114 low, 2 moderate, 11 high, 2 critical)
pm audit fix` to fix them, or `npm audit` for details
pbox\mapbox-gl-js> yarn install
tall v1.22.4
package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by u
nized lock files. To clear this warning, remove package-lock.json.
lidating package.json...
solving packages...
tching packages...
vents@2.1.2: The platform "win32" is incompatible with this module.
events@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
vents@1.2.12: The platform "win32" is incompatible with this module.
events@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
nking dependencies...
" > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
" > @mapbox/mapbox-gl-rtl-text@0.2.3" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
ilding fresh packages...
Saved lockfile.
263.11s.
pbox\mapbox-gl-js>
`

**Comment by dhritzkiv** [comment]
gl@4.5.3 definitely fixes the issue for you, since it installs the binaries without needing to build them with a compiler.

Feel free to open a PR in the mapbox-gl-js repo to update their package.json file to help other Windows users like you. Link the PR here, and I'll add more details to it.

**Comment by ATerentjev** [comment]
I tried to open PR : [https://github.com/mapbox/mapbox-gl-js/pull/9901](https://github.com/mapbox/mapbox-gl-js/pull/9901)
