### ISSUE TITLE
Missing support for WebGL OES_vertex_array_object

### ISSUE THREAD

**Issue by erikmchut** [stackgl/headless-gl#204]
VertexArrayObjects are common GL functionality, exposed in WebGL1 via the OES_vertex_array_object extension. Would it be possible to add support for this?

https://developer.mozilla.org/en-US/docs/Web/API/OES_vertex_array_object

**Comment by dhritzkiv** [comment]
Hi @erikmchut.

Looking over the MDN page, it looks like it should be possible to add it! However, it does appear to be slightly more complicated than some of the more recently implemented extensions as it has methods to return a new objects and manage state.

I currently don't have much time to implement it myself, especially as I've personally never used that extension. That being said, feel free to try adding it yourself. Look into the last few PRs that have added extensions for inspiration: #203, #202, #199

**Comment by erikmchut** [comment]
Thanks for the pointers.

**Comment by erikmchut** [comment]
Hi @dhritzkiv, I created pull request #206 for this, please take a look. It turned out to be more involved than expected, but the gl-compliance tests provided great test coverage to work through all of the issues.
