### ISSUE TITLE
possible attribute location bug

### ISSUE THREAD

**Issue by ansis** [stackgl/headless-gl#21]
I extracted a test case from https://github.com/mapbox/mapbox-gl-js/issues/1449:

https://github.com/ansis/headless-gl/commit/d151bce8c4660b8ba717a4f6fec2e31fe4943691

The 1st and 3rd tests fail for me.

Do you think this is a bug in headless-gl or do you see something wrong with the test case?

**Comment by mikolalysenko** [comment]
This is almost certainly a bug in headless-gl.  Earliest I can get to it is Friday unfortunately, but I think that it shouldn't be too hard to sort out.

**Comment by mikolalysenko** [comment]
Fixed in gl@2.1.1
