### ISSUE TITLE
building on the raspberry pi rasbian jessie

### ISSUE THREAD

**Issue by abrown28** [stackgl/headless-gl#22]
Trying to install it on a raspberry pi with rasbian jessie installed and getting the below error.
It's failing to compile the libAngle library but it looks like that is for converting from opengl es to directx which doesn't make sense for linux. I'm probably wrong :)

**Entire output:**

    $ npm install gl
    npm WARN package.json svg2txt@1.0.0 No description
    npm WARN package.json svg2txt@1.0.0 No repository field.
    npm WARN package.json svg2txt@1.0.0 No README data
    /
    > gl@2.1.0 install /home/abrown28/svg2txt/node_modules/gl
    > node-gyp rebuild
    
    child_process: customFds option is deprecated, use stdio instead.
    make: Entering directory '/home/abrown28/svg2txt/node_modules/gl/build'
      CXX(target) Release/obj.target/angle_common/angle/src/common/Float16ToFloat32.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/MemoryBuffer.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/angleutils.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/debug.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/mathutil.o
    ../angle/src/common/mathutil.cpp: In function ‘unsigned int gl::convertRGBFloatsTo999E5(float, float, float)’:
    ../angle/src/common/mathutil.cpp:55:52: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return *reinterpret_cast<unsigned int*>(&output);
                                                            
      CXX(target) Release/obj.target/angle_common/angle/src/common/string_utils.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/tls.o
      CXX(target) Release/obj.target/angle_common/angle/src/common/utilities.o
      AR(target) Release/obj.target/angle/src/angle_common.a
      COPY Release/angle_common.a
      COPY Release/obj/gen/angle/id/commit.h
      TOUCH Release/obj.target/angle/src/commit_id.stamp
      CXX(target) Release/obj.target/libANGLE/angle/src/common/event_tracer.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/AttributeMap.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Buffer.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Caps.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Compiler.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Config.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Context.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Data.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Device.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Display.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Error.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Fence.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Framebuffer.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/FramebufferAttachment.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/HandleAllocator.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Image.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/ImageIndex.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/IndexRangeCache.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Platform.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Program.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Query.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/RefCountObject.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Renderbuffer.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/ResourceManager.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Sampler.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Shader.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/State.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Surface.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Texture.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/TransformFeedback.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/Uniform.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/VertexArray.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/VertexAttribute.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/angletypes.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/formatutils.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/queryconversions.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/DeviceImpl.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/DisplayImpl.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/ProgramImpl.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/Renderer.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/SurfaceImpl.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/validationEGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/validationES.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/validationES2.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/validationES3.o
      CXX(target) Release/obj.target/libANGLE/angle/src/third_party/murmurhash/MurmurHash3.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/BufferGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/CompilerGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/DisplayGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/FenceNVGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/FenceSyncGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/FramebufferGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/FunctionsGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/ProgramGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/QueryGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/RenderbufferGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/RendererGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/ShaderGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/StateManagerGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/SurfaceGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/TextureGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/TransformFeedbackGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/VertexArrayGL.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/formatutilsgl.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/renderergl_utils.o
      CXX(target) Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/glx/DisplayGLX.o
    ../angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp: In member function ‘virtual egl::Error rx::DisplayGLX::initialize(egl::Display*)’:
    ../angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp:134:49: error: ‘contextConfig’ was not declared in this scope
             mContext = mGLX.createContextAttribsARB(contextConfig, nullptr, True, nullptr);
                                                         
    ../angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp:137:42: error: ‘contextConfig’ was not declared in this scope
             mContext = mGLX.createNewContext(contextConfig, GLX_RGBA_TYPE, nullptr, True);
                                                  
    ../angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp:155:9: warning: unused variable ‘pbufferAttribs’ [-Wunused-variable]
         int pbufferAttribs[] = { 0 };
                 
    angle/src/libANGLE.target.mk:207: recipe for target 'Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/glx/DisplayGLX.o' failed
    make: *** [Release/obj.target/libANGLE/angle/src/libANGLE/renderer/gl/glx/DisplayGLX.o] Error 1
    make: Leaving directory '/home/abrown28/svg2txt/node_modules/gl/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
    gyp ERR! System Linux 4.1.6-v7+
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/abrown28/svg2txt/node_modules/gl
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok
    npm ERR! Linux 4.1.6-v7+
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gl"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! gl@2.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the gl@2.1.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the gl package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls gl
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/abrown28/svg2txt/npm-debug.log

**Comment by bsergean** [comment]
I got the same problem while building on Centos 7.1

I've filled an issue on the libANGLE project / hopefully someone will look at it =>
https://code.google.com/p/angleproject/issues/detail?id=1154

**Comment by mikolalysenko** [comment]
The issues should be fixed in the next version, will push it out today once I get all the prebuilds working.

**Comment by mikolalysenko** [comment]
Try out gl@2.1.2, it should be better now.

**Comment by bsergean** [comment]
Build fix works great for me, thanks for the quick fix !

But since I'm a troublemaker I have a different problem now that should go in a different issue I think.
