### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by huangzongwang** [stackgl/headless-gl#227]
webgl.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::shared_p
tr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?
AV?$shared_ptr@VBackingStore@v8@@@std@@XZ)，该符号在函数 "public: __cdecl Nan::TypedArrayContents<char>::TypedArrayContents<char>(class v8::Local<class v8::Value>)" (??0?$TypedArrayContents@D@Nan@@QEAA@V?$Local@VVa
lue@v8@@@v8@@@Z) 中被引用 [D:\gy\videos\node_modules\gl\build\webgl.vcxproj]
D:\gy\videos\node_modules\gl\build\Release\webgl.node : fatal error LNK1120: 1 个无法解析的外部命令 [D:\gy\videos\node_modules\gl\build\webgl.vcxproj]

**Comment by dhritzkiv** [comment]
What version of node js are you installing this on? Which Windows are you installing it on? Is it 64-bit or 32-bit?

**Comment by huangzongwang** [comment]
window10 node.js64

**Comment by huangzongwang** [comment]
> 

window10 node.js64

**Comment by dhritzkiv** [comment]
Is your Node JS version 12, 14, 16? Or another, such as 17?

**Comment by huangzongwang** [comment]
16.14.0

**Comment by huangzongwang** [comment]
> 您的 Node JS 版本是 12、14、16 吗？或者另一个，比如17？

16.14.0

**Comment by dhritzkiv** [comment]
OK. Thank you.

Does this happen when you run `npm install gl`  or `npm install`?

**Comment by dhritzkiv** [comment]
Part of the `npm install gl` process is that 'npm' installs the prebuilt binaries that are included for the release: see them here: https://github.com/stackgl/headless-gl/releases/tag/v5.0.0

The one that should install for you is [gl-v5.0.0-node-v93-win32-x64.tar.gz](https://github.com/stackgl/headless-gl/releases/download/v5.0.0/gl-v5.0.0-node-v93-win32-x64.tar.gz)

Because it's prebuilt, you should not need to compile.

**Comment by huangzongwang** [comment]
> Part of the `npm install gl` process is that 'npm' installs the prebuilt binaries that are included for the release: see them here: https://github.com/stackgl/headless-gl/releases/tag/v5.0.0
> 
> The one that should install for you is [gl-v5.0.0-node-v93-win32-x64.tar.gz](https://github.com/stackgl/headless-gl/releases/download/v5.0.0/gl-v5.0.0-node-v93-win32-x64.tar.gz)
> 
> Because it's prebuilt, you should not need to compile.

Thank you

**Comment by dhritzkiv** [comment]
The file(s) should go in: `node_modules\gl\build\Release\`

**Comment by huangzongwang** [comment]
> node_modules

ok,Thank you

**Comment by huangzongwang** [comment]
> The file(s) should go in: `node_modules\gl\build\Release\`

electron-rebuild Can I compile GL? Are there any version requirements

**Comment by huangzongwang** [comment]
> The file(s) should go in: `node_modules\gl\build\Release\`

electron-rebuild Can I compile GL? Are there any version requirements
