### ISSUE TITLE
extractImageData does not set dimensions of Canvas before drawing pixels

### ISSUE THREAD

**Issue by coeing** [stackgl/headless-gl#232]
https://github.com/stackgl/headless-gl/blob/ba03b7d31903af6dcc228bc6b83a64ea247e18d6/src/javascript/utils.js#L147

Hi there!

First of all thanks for your great package! It really helps with the task I am currently working on 👍 

I think I found a bug inside `extractImageData`: A canvas element is created there, but its width/height is never set. So it might be too small to contain the pixels that are written into it by `drawImage`. This leads to a cropped result.

Those two lines below the creation of the canvas should solve the issue:
``` 
canvas.width = pixels.width;
canvas.height = pixels.height;
```

Background: I am using your package to make PixiJS run in a NodeJS environment. It's a bit hacky but works in general. For the required canvas element the `canvas` NPM package is used.

**Comment by dhritzkiv** [comment]
Good catch! Do you mind creating a PR with this fix?

**Comment by dhritzkiv** [comment]
I suspect putting that snippet just before [`context = canvas.getContext('2d')`](https://github.com/stackgl/headless-gl/blob/ba03b7d31903af6dcc228bc6b83a64ea247e18d6/src/javascript/utils.js#L144) makes most sense

**Comment by coeing** [comment]
> I suspect putting that snippet just before [`context = canvas.getContext('2d')`](https://github.com/stackgl/headless-gl/blob/ba03b7d31903af6dcc228bc6b83a64ea247e18d6/src/javascript/utils.js#L144) makes most sense

@dhritzkiv True that :) Will create a PR tomorrow!
