### ISSUE TITLE
Prebuilding Node v16 version for macOS

### ISSUE THREAD

**Issue by stepankuzmin** [stackgl/headless-gl#237]
Hi,

I've tried to enable [the Node v16 build for macOS](https://github.com/stepankuzmin/headless-gl/pull/1/files) with `xcode13.4`, and it seems to be working fine https://github.com/stepankuzmin/headless-gl/pull/1/checks?check_run_id=8345225303

Is there any chance we can enable prebuilding Node v16/v18 versions for macOS?

**Comment by mourner** [comment]
Hey @dhritzkiv, gently bumping this up for visibility 🙏

**Comment by dhritzkiv** [comment]
Closed by f97ba1596597d1743b375ce7bc6905bf4f0fd87d

**Comment by dhritzkiv** [comment]
That said, I'm having trouble releasing it, as I can't get prebuilds in Linux/macOS to properly occur in CI.

Specifically, I'm having this error: https://github.com/nodejs/node-gyp/issues/2673 which prevents building for older node versions. This error is where an irrelevant variable (openssl_fips) is no longer defined, somewhere. Unfortunately, it looks like the workaround is to add it to EVERY .gyp file in the project, including sub dependencies, which might not be doable. It also doesn't help that building locally vs. in CI is giving me different outcomes.

**Comment by mourner** [comment]
@dhritzkiv should this be reopened? Still not able to install `gl` v6.0.1 for both Node v16 and v18 on macOS...

**Comment by dhritzkiv** [comment]
Oh no! I had to revert the changes, due to [CI problems](https://github.com/stackgl/headless-gl/runs/8808311645), and then I had to manually prebuild + upload the binaries from my machine, making sure to build for v18, v16, and v14.

The binaries appear to be present [under the release](https://github.com/stackgl/headless-gl/releases/tag/v6.0.1) (see darwin-x64) so I wonder what's going on…

@mourner is your machine an Apple Silicon Mac? what's the exact output that you see when you try to install?

**Comment by stepankuzmin** [comment]
Yes, it can't find prebuilt binaries for the Apple Silicon Mac.

```shell
npm i gl@6.0.1

...

prebuild-install warn install No prebuilt binaries found (target=18.11.0 runtime=node arch=arm64 libc= platform=darwin)
```

**Comment by dhritzkiv** [comment]
@stepankuzmin Ah! OK. I have yet to work with macOS arm64 prebuilds. I'll look into generating those on my machine (still an Intel).

Unfortunately, CI problems aside, this PR would not have generated those binaries. :(

**Comment by dhritzkiv** [comment]
I uploaded a binary that built for node 18 + arm64 but I have no idea if that worked or not. @stepankuzmin could you try now?

**Comment by stepankuzmin** [comment]
@dhritzkiv it's working now! 🎉
