### ISSUE TITLE
get a black image in centos7.9

### ISSUE THREAD

**Issue by vvshuai** [stackgl/headless-gl#249]
I had no problems running the code on a Windows 10 system, but when I ran the same code on a CentOS 7 without graphics, I got a black image and no error messages.
I have confirmed that Mesa, X11, and Xvfb are installed, and I am using Xvfb to run the code.
env:
- OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.4
- OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

**Comment by vvshuai** [comment]
On a headless Linux machine，I found that the GL_OES_texture_float extension did not work, which caused a failure when using gl.Float, but I couldn't locate the problem.

**Comment by vvshuai** [comment]
I was able to run it successfully on the Debian, but it failed on CentOS 7.9. 
I suspect it is due to the version issue of Mesa. 
GL_OES_texture_float is not supported on OpenGL ES 2.0 Mesa 18.3.4.
I will close this issue.

**Comment by dhritzkiv** [comment]
Sorry I didn't get to your issue sooner. I am glad you figured it out yourself, and have updated the thread. Thank you.
