### ISSUE TITLE
GL extension support

### ISSUE THREAD

**Issue by bsergean** [stackgl/headless-gl#27]
There does not seem to be any code to support GL extensions. I wonder what it would take to add this.

```
GL_METHOD(GetSupportedExtensions) {
  GL_BOILERPLATE;
  char *extensions=(char*) glGetString(GL_EXTENSIONS);
  NanReturnValue(NanNew<v8::String>(extensions));
}

GL_METHOD(GetExtension) {
  GL_BOILERPLATE;

  //TODO

  NanReturnUndefined();
}
```

**Comment by mikolalysenko** [comment]
Yes, this is a duplicate of #5 .  Once the conformance suite passes on windows, OS X and linux I'll work on this.

**Comment by bsergean** [comment]
Ah ok. I'll close this then.
