### ISSUE TITLE
Build fail from node 20.5.0

### ISSUE THREAD

**Issue by Pnlvfx** [stackgl/headless-gl#272]
I've tested it until 20.3.0 and it's working. I think that could be added the engines field on the package.json to let people know the latest supported version

**Comment by Pnlvfx** [comment]
Any plan to this?

**Comment by dhritzkiv** [comment]
Try the latest version: [v8.0.2](https://github.com/stackgl/headless-gl/releases/tag/v8.0.2). Installing / building should now work with node 20.
