### ISSUE TITLE
Publishing 7.0.0

### ISSUE THREAD

**Issue by ilijapuaca** [stackgl/headless-gl#273]
I was wondering if there are plans on publishing 7.0.0 to npm? As far as I can tell `master` seems good to go for the release and the version bump has already happened, it'd help tremendously with our upgrade to Node 20 by having the pre-built binaries available under the new release

**Comment by dhritzkiv** [comment]
[v8.0.2](https://github.com/stackgl/headless-gl/releases/tag/v8.0.2) is out instead. It fixes building for node 20 on recent compilers, and includes prebuilt binaries. The main thing holding the release back was CI troubles! * shakes fist *

**Comment by ilijapuaca** [comment]
Thank you for following up!
