### ISSUE TITLE
Could you please kindly add the new version to npmjs.com?

### ISSUE THREAD

**Issue by xeoshow** [stackgl/headless-gl#276]
Hello, 

I found in the gitub.com, headless-gl has already got the new Tags with v7.0.0, v8.0.0, v8.0.1, v8.0.2, since v6.0.2 was released two years ago, hopefully there could be some new versions added, could you please kindly add them? We just would like to get the new nodejs version be supported. Thanks a lot. 
```
https://www.npmjs.com/package/gl?activeTab=versions

PS D:\zztest> pnpm view gl versions
[
  '0.0.0', '0.0.1', '0.0.2',
  '0.0.5', '2.0.0', '2.1.0',
  '2.1.1', '2.1.2', '2.1.3',
  '2.1.4', '2.1.5', '3.0.3',
  '3.0.5', '3.0.6', '4.0.0',
  '4.0.1', '4.0.2', '4.0.3',
  '4.0.4', '4.1.1', '4.2.2',
  '4.3.0', '4.3.1', '4.3.2',
  '4.3.3', '4.4.0', '4.4.1',
  '4.5.0', '4.5.2', '4.5.3-win64.0',
  '4.5.3', '4.6.0', '4.6.1',
  '4.7.0', '4.8.0', '4.9.0',
  '4.9.2', '5.0.0', '5.0.3',
  '6.0.1', '6.0.2'
]
```

**Comment by xeoshow** [comment]
Hello @dhritzkiv ,

First, great thanks for your this project!
And I just checked, v8.0.2, seems got below failure, will this affect the publish process to npmjs.com? Sorry for bothering ask this since I am not familar with the publish process. 
![image](https://github.com/stackgl/headless-gl/assets/1164284/65c9e6f5-f663-4a3b-a019-83505fc09723)

The details of the failure:
https://ci.appveyor.com/project/dhritzkiv/headless-gl/builds/49304023

Thanks again!

Best regards, Jason

**Comment by dhritzkiv** [comment]
Should be out as [v8.0.2](https://github.com/stackgl/headless-gl/releases/tag/v8.0.2), which includes prebuilt binaries for linux and macOS. The release also includes fixes for building with more recent c++ compilers.

Unfortunately, I am unable to produce a Windows prebuilt binary. It relies on the Appveyor deployment, which as you've mentioned in your screenshot, failed. I've tried for several days (over many months) to fix it with no luck.

We've always had trouble with appveyor/Windows and running tests + producing prebuilt binaries for Windows. Unless someone is able to assist in getting the appveyor CI working, or is able to help with getting GitHub Actions set up for this repo, I don't foresee Windows prebuilds coming any time soon.
