### ISSUE TITLE
Does it works on replit?

### ISSUE THREAD

**Issue by onchainyaotoshi** [stackgl/headless-gl#277]
I also try to running with below scripts:
xvfb-run :99 -screen 0 1280x1024x24 & export DISPLAY=:99; npm run start:live
xvfb-run :99 -screen 0 1024x768x24 & export DISPLAY=:99; npm run start:live
xvfb-run -s "-ac -screen 0 1024x768x24" npm run start:live
xvfb-run --auto-servernum --server-num=1 -s "-ac -screen 0 1280x1024x24" npm run start:live

with gl version:  "^6.0.2",

Errors:

THREE.WebGLRenderer: Error creating WebGL context.
file:///home/runner/frame-cube/node_modules/three/build/three.module.js:28929
                        throw new Error( 'Error creating WebGL context.' );
                              ^

Error: Error creating WebGL context.
    at new WebGLRenderer (file:///home/runner/frame-cube/node_modules/three/build/three.module.js:28929:13)
    at CubeView.initScene (file:///home/runner/frame-cube/src/utils/rubik/cube-view.js:34:21)
    at new CubeView (file:///home/runner/frame-cube/src/utils/rubik/cube-view.js:12:10)
    at Rubik.renderToBase64 (file:///home/runner/frame-cube/src/utils/rubik/index.js:23:17)
    at renderFrameUnsolvedRubik (file:///home/runner/frame-cube/src/controllers/rubik-controller.js:32:18)
    at startSession (file:///home/runner/frame-cube/src/controllers/rubik-controller.js:72:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dhritzkiv** [comment]
Hi there.

I'm not familiar with replit, so I can't completely offer any advice on what may be going on there.

What output do you see if you run

```
xvfb-run --auto-servernum -s "-ac -screen 0 1024x768x24" `which glxinfo`
```

**Comment by onchainyaotoshi** [comment]
it's returns:

which: no glxinfo in (/nix/store/d6nl0ycs8kq6w8wi4d2912ngmd1z27k5-getopt-1.1.6/bin:/nix/store/h4c784aqvj7x5450irnh6b4jahjynrpi-xorg-server-21.1.9/bin:/nix/store/n3kygy581jq57q9lw79qg5029nn14fni-xauth-1.1.2/bin:/nix/store/d8hffavh8b4fs4bw135gkflx5aimcff3-which-2.21/bin:/nix/store/wijccjzl2g8knym08ixzbhqp06p8d2ck-util-linux-2.39.2-bin/bin:/nix/store/7wfya2k95zib8jl0jk5hnbn856sqcgfk-gawk-5.2.2/bin:/nix/store/bblyj5b3ii8n6v4ra0nb37cmi3lf8rz9-coreutils-9.3/bin:/nix/store/x88ivkf7rmrhd5x3cvyv5vh3zqqdnhsk-bash-interactive-5.2-p15/bin:/nix/store/85jldj870vzcl72yz03labc93bwvqayx-patchelf-0.15.0/bin:/nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin:/nix/store/hf2gy3km07d5m0p1lwmja0rg9wlnmyr7-gcc-12.3.0/bin:/nix/store/cx01qk0qyylvkgisbwc7d3pk8sliccgh-glibc-2.38-27-bin/bin:/nix/store/1alqjnr40dsk7cl15l5sn5y2zdxidc1v-binutils-wrapper-2.40/bin:/nix/store/1fn92b0783crypjcxvdv6ycmvi27by0j-binutils-2.40/bin:/nix/store/hxpwfhslscfak9vh9ksxbzzpbkqlspgh-postgresql-15.5/bin:/nix/store/a1hckfqzyys4rfgbdy5kmb5w0zdr55i5-nodejs-20.9.0/bin:/nix/store/2miairdnqbrsjlcllj2vypnvmk2k9z6j-python3-3.10.13/bin:/nix/store/cnsbbj66kz0fdp41xhy9nd45pashpai7-gnumake-4.4.1/bin:/nix/store/ljrkf0kwgckcy02kdlz8sjdnxb2pwjb4-pkg-config-wrapper-0.29.2/bin:/nix/store/yjrydicl01j1h6dj8km1w2n3lfsnz21y-xvfb-run-1+g87f6705/bin:/nix/store/626czg4kg8hfka309snknbm0dnj2ygpj-libdrm-2.4.117-bin/bin:/nix/store/fp5d6vbgqrqpmr6sqk58jvqzfnrwp0dj-mesa-23.1.9/bin:/nix/store/mx2rrqxmr2yp98w40rx6kvmdxsmk8s7z-libdrm-2.4.117-bin/bin:/nix/store/wffx3zj91335jp42qxyb0gw72q1r8d2h-mesa-23.1.9/bin:/nix/store/wy8zlrxhdj04pi3wl93jig6im6akps7q-glew-2.2.0-bin/bin:/nix/store/qm4w9jdpw01p9sim0lin2lfhnqlnhx6a-cairo-1.18.0-dev/bin:/nix/store/4q1b6baa364dx88s3h5dz4np2a0zsnrl-freetype-2.13.2-dev/bin:/nix/store/ik7jardq92dxw3fnz3vmlcgi9c8dwwdq-bzip2-1.0.8-bin/bin:/nix/store/811x5ncd30pf8ll89xq02jbnh4883220-brotli-1.1.0/bin:/nix/store/j239iqdfsmz527i28pqw9b48dq31kimv-libpng-apng-1.6.40-dev/bin:/nix/store/iz4i4zj4bz7p71zs8lqcwi5v090xsdc2-fontconfig-2.14.2-bin/bin:/nix/store/ybmdzvab1s6hfkfj4hm848pgdxzlc36g-glib-2.78.1-dev/bin:/nix/store/wxjk2v5vjxmpm7lkiy0mk9xcqcrhp007-gettext-0.21.1/bin:/nix/store/m42y05yfzrlf41i22rznw015gxrina43-glib-2.78.1-bin/bin:/nix/store/5qlry8s28q321mgak217l655byddnwqh-harfbuzz-7.3.0-dev/bin:/nix/store/l0zdl1j9gc4w9j5b5k725m8fhlvmx7cb-graphite2-1.3.14/bin:/nix/store/7r7gdacmskgmzhgfy9vc84ap64l5738z-pango-1.51.0-bin/bin:/nix/store/f1v3kr3cdla5cagvfpahkng0vj6ggsfn-libjpeg-turbo-2.1.5.1-bin/bin:/nix/store/iy6zbvrjkwr6kv1a4sbh44s269b8qqx8-giflib-5.2.1/bin:/nix/store/j951is5lyy6v17kq57iqzlihlwnn986j-gdk-pixbuf-2.42.10-dev/bin:/nix/store/9b574szb98l1k3vgjjdqxnbs4104wcvf-libdeflate-1.19/bin:/nix/store/76z4cjs7jj45ixk12yy6k5z2q2djk2jb-xz-5.4.4-bin/bin:/nix/store/ywgvyraw441m30s1vx7vc1rss9sfaia8-libtiff-4.6.0-bin/bin:/nix/store/97iq7h7hap878b2xc5dqfcp89nmnawcb-gdk-pixbuf-2.42.10/bin:/nix/store/6kdk0rn09jjashhcb7yknklsc03dyycm-librsvg-2.57.0/bin:/nix/store/471gz76zfqlnh3jdmyj6ppa0fh42q4a4-util-linux-minimal-2.39.2-bin/bin:/nix/store/jaif1a70s73dx6j3wmxszhs4ghyb91gx-attr-2.5.1-bin/bin:/nix/store/hc0xnmdf4fpp7cyy1p88my82zvm87ph2-libcap-2.69/bin:/nix/store/lnpjvqr1d2lmn5hs732k3llrp06j2p3s-pulseaudio-16.1/bin:/nix/store/l974pi8a5yqjrjlzmg6apk0jwjv81yqw-findutils-4.9.0/bin:/nix/store/8q25nyfirzsng6p57yp8hsaldqqbc7dg-diffutils-3.10/bin:/nix/store/9c5qm297qnvwcf7j0gm01qrslbiqz8rs-gnused-4.9/bin:/nix/store/rx2wig5yhpbwhnqxdy4z7qivj9ln7fab-gnugrep-3.11/bin:/nix/store/xpidksbd07in3nd4sjx79ybwwy81b338-gnutar-1.35/bin:/nix/store/202iqv4bd7lh6f7fpy48p7q4d96lqdp7-gzip-1.13/bin:/nix/store/v4iswb5kwj33l46dyh2zqh0nkxxlr3mz-gnumake-4.4.1/bin:/nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15/bin:/nix/store/cbj1ph7zi009m53hxs90idl1f5i9i941-patch-2.7.6/bin:/nix/store/qmfxld7qhk8qxlkx1cm4bkplg1gh6jgj-file-5.45/bin:/nix/store/yq0vlv3d2f5si3ibawpq5ay2pc6knixp-nix-2.18.0pre20230808_c0e6466/bin:/nix/store/i4kzir3m7mrisxmf5xvlnkw01x4qaqr4-prybar-elisp-0.0.0-e0d9a52/bin:/nix/store/lwwivxf6h7x3cvxp9zv8sj0mv7dak99r-prybar-lua-0.0.0-e0d9a52/bin:/nix/store/gxj28g1cg4hq3qanmjv07156h800qr58-prybar-python3-0.0.0-e0d9a52/bin:/nix/store/hshkjnxrgidigf8x75vg6lqng2xlx9i3-prybar-sqlite-0.0.0-e0d9a52/bin:/nix/store/c4w01bpjgyy5ixmwdk8m1pw87zq4sl26-prybar-tcl-0.0.0-e0d9a52/bin:/nix/store/hpbvrlwd5viqmvcaisb3x0118i913a9n-stderred-0.1.0/bin:/nix/store/c98w73rq49rr8f0lldlf8finwmq0s17x-upm-0.0.0-c1533a6/bin:/nix/store/ljhz8ffrbdmfhcbgp7076mkys79klacx-pid1/bin:/nix/store/ic6qnrphr39fbwjcxkgjp8xlczn15hq1-less-643/bin:/nix/store/whwwhd6ns271bj0ff86ap37i9r9kzi9c-git-2.42.0/bin:/nix/store/r1diwi9xkwqrbkv0mrckh19ppp06r9i4-silver-searcher-2.2.0/bin:/nix/store/ixqgy5s0zr9mricqrv5f4sv6dfky7iz9-bash/bin:/nix/store/vwkvhj69z4qqgmpa2lwm97kabf12p26r-coreutils-9.3/bin:/nix/store/ndx64mdps5p74illylpzq25pi4kbr05x-vscode-cpptools-dap-1.3.1/bin:/nix/store/6lppqybghirwljfwcwbr0z7rzdqncn3j-replit-python-dap-wrapper-1.0.0/bin:/nix/store/36pkp8h1i81xmdc892awly75l8gifmgl-node-dap/bin:/nix/store/k4ww8n0mqbx5ff0aj90jnqi0swr8akla-pydeppaths-1.0.0/bin:/nix/store/90hs7aipck6vz90xpdyb6vjjzlr7ci64-fluxbox/bin:/nix/store/qpnf0dafrfsbcwb4z7cphjm0dff0vl7l-prybar-nodejs-0.0.0-e0d9a52/bin:/nix/store/p109137pdyy3l8xjzd2zwknhc2l4yj5a-pulseaudio-16.1/bin:/nix/store/146hw02zpnhkn5cabjf3pmdl32clz0jn-rfbproxy-0.0.0-9c8ca29/bin:/nix/store/g5vyafx7amin9rv99npzz54bgp437kgd-toml-editor-0.0.0-d7dc78d/bin:/nix/store/mi0by7pw54j7nn8a9pp8z03rghfhb2ba-nix-editor-0.0.0-fb83e47/bin:/nix/store/xxwdh0kcj077br5vy2kpi6bznwlq6axi-tigervnc-1.13.1/bin:/nix/store/kxxmdnyk9zhn52v8yhjksiq2cx90vyd2-xwininfo-1.1.6/bin:/nix/store/pv89r9i1d8ajin2vp7qfs63nakg7s17k-replbox/bin:/nix/store/0g1lq3vff290wainxdlbz9a18m28pr4r-curl-8.4.0-bin/bin:/nix/store/f5qy259g9b4qh0hwz22z5j5bq3m53cpv-gnutar-1.35/bin:/nix/store/3nbvki8kpyni8nq8q6dbzhrmrpgcbvyz-libglvnd-1.6.0/bin:/nix/store/x8gff7zw0xn2kzj0xi36kwkwh5irl9mw-ripgrep-13.0.0/bin:/nix/store/xnrc27zfxhpwbd8gcmfyh36r4wa5l72j-sd-0.7.6/bin:/nix/store/412vmy2s2w63653mfnk3p6w8m1mbvcwq-apt-get/bin:/nix/store/s50yw8wrq90ajh6q2yg8by4jk0c48ig4-apt/bin:/nix/store/jj38yn79vfwpsasrvg63kz3q3znni1i8-sudo/bin:/nix/store/252w9k71955a6g4ym4646x35ixwhxbmw-replit-git-askpass/bin:/nix/store/wz8sm86f9vp5y10r62j4afxqr8dd28fl-replit-git-editor/bin:/nix/store/n0ldnqg7x2alq0smwb3sw08n9m5rav1i-xdg-open/bin:/nix/store/w8jl7avpp9sw6jaskrhwb9qcal3axgrk-moduleit/bin:/nix/store/dl75qyfhf1s243h5a1cjwsc1ddsdrrq8-hostingpid1-1.0.8/bin:/nix/store/zlzz2z48s7ry0hkl55xiqp5a73b4mzrg-gcc-wrapper-12.3.0/bin:/nix/store/rzqd859mqsxq4w32lzgbmwlv68sxwwmw-gnumake-4.4.1/bin:/nix/store/329fjnc15vmxw50wgxlc1vrpmzbymwdp-rippkgs-0.1.0/bin:/nix/store/xp87fgwla0d84za1m3mviq9hi6ik3gq9-rippkgs-index-0.1.0/bin:/nix/store/nca9ffbfh83d1r2cqg26ljmgj447ilri-man-db-2.11.2/bin:/nix/store/83qm9rii0sd5251bjv8344bz9gg423a9-direnv-2.32.3/bin:/home/runner/.nix-profile/bin:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

**Comment by onchainyaotoshi** [comment]
so i manage to install glxinfo and it returns:

/nix/store/00rxyj8xxpq1sadd3adm6q6ls7hx0rmx-mesa-demos-9.0.0/bin/glxinfo

if i run glxinfo without xvfb:

name of display: :0
Error: couldn't find RGB GLX visual or fbconfig

**Comment by onchainyaotoshi** [comment]
so i create a file check-gl.js to test it on replit which is a linux platform too.

```
import createGL from 'gl';

function delay(time) {
  return new Promise(resolve => setTimeout(resolve, time));
} 

const ctx = createGL(300, 300);
console.log("ctx", null);

await delay(5000);
throw new Error('finish');
```

and i run the script with:

`xvfb-run --auto-servernum -s "-ac -screen 0 1024x768x24" node ./scripts/check-gl.js`

and the result is "ctx null"

![Screenshot_54](https://github.com/stackgl/headless-gl/assets/142854977/352feebf-72c1-4a06-9116-67b07fa27347)

**Comment by dhritzkiv** [comment]
Have you made sure to install the relevant dependencies for your system?

- mesa-utils
- libgl1-mesa-dri
- libglapi-mesa
- libosmesa6

Note: these dependencies vary by system, and I'm not familiar with the replit environment, so I can't advise more specifically.

**Comment by onchainyaotoshi** [comment]
I have installed all the necessary packages through replit.nix. Without these installations, the node-gyp build phase would not complete successfully

{ pkgs }: {
  
  deps = [
      pkgs.vim-full
      pkgs.pciutils
    pkgs.postgresql
    pkgs.nodejs_20
    pkgs.python310Full

    #for node-gyp (build-essential)
    pkgs.gcc
    pkgs.gnumake

    #for gl & canvas
    pkgs.pkg-config
    pkgs.xvfb-run
  
    #for gl node-gyp build
    pkgs.mesa
    pkgs.mesa-demos

    #for fix couldn't find RGB GLX visual or fbconfig when run this shell command: xvfb-run --auto-servernum -s "-ac -screen 0 1024x768x24" glxinfo

    #for canvas 
    pkgs.cairo
    pkgs.pango
    pkgs.libjpeg
    pkgs.giflib
    pkgs.librsvg
    pkgs.libuuid
    pkgs.binutils
    
    # Add other dependencies here
  ];

  #https://github.com/Automattic/node-canvas/issues/1893#issuecomment-1096988007
  env = { 
    LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
      pkgs.libuuid
    ];
    PYTHONHOME = "${pkgs.python310Full}";
    PYTHONBIN = "${pkgs.python310Full}/bin/python3.10";
    LANG = "en_US.UTF-8";
  }; 
}

**Comment by onchainyaotoshi** [comment]
So, I am considering leaving it as is and migrating to another hosting site. Do you have any suggestions for hosting sites that might support these packages?

**Comment by dhritzkiv** [comment]
Glad you were able to get it to work.

Generally, it shouldn't depend on a specific hosting provider – it more so depends on the environment that you're trying to get it to work in, and what complications/restrictions it imposes. It's possible with more work you might have been able to get it set up in Replit/Nix, but it seems like there were an unknown number of obstacles in the way.
