### ISSUE TITLE
This project will not compile on GCC >= 13 due to missing includes for <cstdint>

### ISSUE THREAD

**Issue by ILOVEPIE** [stackgl/headless-gl#288]
This is due to GCC not including the header by default anymore for C++.

**Comment by dhritzkiv** [comment]
This should be resolved as of 14cf7f3b7ebd02e58b7cb97888a197b7a76121ec, which is in 8.x of this library. Are you finding that it's not?

**Comment by ILOVEPIE** [comment]
nevermind, I just realized that it's probably the library I'm using that specified an older version of this library.
