### ISSUE TITLE
Build broken for node v4

### ISSUE THREAD

**Issue by mikolalysenko** [stackgl/headless-gl#29]

**Comment by mikolalysenko** [comment]
Might we worth looking at alternatives to NAN: https://github.com/nodejs/nan/issues/455

**Comment by bsergean** [comment]
@mikolalysenko Given that the node v4 transition is not gonna be that smooth, what do you think about making a new build for the currently supported node versions so that the Linux angle fix can be picked up and available from npm install ?

**Comment by ronkorving** [comment]
@mikolalysenko After reading that thread, it seems NAN is back in business for headless-gl? :)

**Comment by mikolalysenko** [comment]
Yes, once I get the PR landed

**Comment by ronkorving** [comment]
Good luck!

**Comment by mikolalysenko** [comment]
Ok, in the interest of making progress here I temporarily forked nan to get the necessary features.  Once https://github.com/nodejs/nan/pull/459 or something like it gets merged I'll switch back.
