### ISSUE TITLE
Prebuild-install not found with v8.1.0 on Windows x64 with Nodejs v20.12.2

### ISSUE THREAD

**Issue by harryhongkh** [stackgl/headless-gl#301]
`npm build gl`
![image](https://github.com/user-attachments/assets/229ecc80-9711-4c05-8c60-284d5c98cfb2)
NODE
![image](https://github.com/user-attachments/assets/5d76a855-265e-4dff-8897-a12787f6b25d)

**Comment by dhritzkiv** [comment]
Could you perform these steps to help me debug this?

1. `git clone` this repo
2. `cd` into the repo's directory
3. run `npx prebuild-install --download --verbose`

Then paste the output into a comment

**Comment by harryhongkh** [comment]
Need to install the following packages:
prebuild-install@7.1.2
Ok to proceed? (y)
prebuild-install info begin Prebuild-install version 7.1.2
prebuild-install info looking for local prebuild @ prebuilds\gl-v8.1.0-node-v115-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Harry.Hong\AppData\Local\npm-cache\_prebuilds\ded633-gl-v8.1.0-node-v115-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Harry.Hong\AppData\Local\npm-cache\_prebuilds\ded633-gl-v8.1.0-node-v115-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\Harry.Hong\test\headless-gl\build\Release\webgl.node
prebuild-install warn install The specified module could not be found.
\\?\C:\Users\Harry.Hong\test\headless-gl\build\Release\webgl.node

**Comment by dhritzkiv** [comment]
Thank you. 

Looks like the prerelease artifact/file (v8.1.0-node-v115-win32-x64.tar.gz) does exist (and was written to `C:\Users\Harry.Hong\test\headless-gl\build\Release\webgl.node`)  but it fails to install correctly.

**Comment by dhritzkiv** [comment]
I suspect that part of the binary wasn't uploaded correctly to the GitHub release. Most likely the dll is missing.

Are you able to still install the `gl` package, without the prebuilt binary?

**Comment by harryhongkh** [comment]
We would wait for the pre-built to align the envs
:) thanks for looking into it.
 ❤️ from Toronto.

**Comment by harryhongkh** [comment]
Any update to this? ~~

**Comment by dhritzkiv** [comment]
See if v8.1.5 works for you. This release should have all the required files.
