### ISSUE TITLE
"npm i" error

### ISSUE THREAD

**Issue by whatisor** [stackgl/headless-gl#43]
Hello,
I am on Window 8.1 64bit with nodejs 0.10
I cannot install gl module.
Here is log:
$ npm i
npm WARN package.json Door@0.0.1 No repository field.
npm WARN package.json Door@0.0.1 No README data

> gl@2.1.5 install F:\Data\git\door\node_modules\gl
> prebuild --download

prebuild WARN install Prebuilt binaries for node version v0.10.29 are not available
prebuildnpm ERR! gl@2.1.5 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gl@2.1.5 install script.
npm ERR! This is most likely a problem with the gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls gl
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! cwd F:\Data\git\door
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE

Thank you

**Comment by whatisor** [comment]
it works on Ubuntu, but not Windows.

**Comment by mikolalysenko** [comment]
Upgrade your node to something more recent.  node 0.10 is unsupported and also doesn't have nan bindings.
