### ISSUE TITLE
Texture does not work

### ISSUE THREAD

**Issue by whatisor** [stackgl/headless-gl#45]
Texture does not work without any error logging.
I use data from this :
 //create image data
		
var canvas = document.createElement('canvas'),
    				ctx = canvas.getContext('2d');
    				ctx.drawImage(image, 0, 0);

			        //now we can finally get a Uint8ClampedArray
			        var imageData = ctx.getImageData(0, 0, image.width, image.height);
				image =  imageData;

Then pass image to texImage2D

**Comment by mikolalysenko** [comment]
`headless-gl` doesn't support image data or implement the canvas 2D API.  If you want to use a texture, you'll need to unpack the pixels into a typedarray and initialize it manually.
