### ISSUE TITLE
Windows installation/compiling does not work

### ISSUE THREAD

**Issue by dfcreative** [stackgl/headless-gl#49]
Hi! Insalling in windows gives this:
```sh
prebuild ERR! stack Error: Invalid version number: 0.10.40,0.12.7,1.0.4,1.8.4,2.4.0,3.3.1,4.2.2,5.0.0,5.3.0
```

**Comment by dfcreative** [comment]
`prebuild --download`, if it didn’t find the version, does not start `node-gyp rebuild`, but just throws error and stop process.
After `node-gyp build` manually I get:
```sh
webgl.obj : error LNK2001: unresolved external symbol __imp_eglDestroyContext [
c:\Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglMakeCurrent [c:\
Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglInitialize [c:\U
sers\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglChooseConfig [c:
\Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglCreatePbufferSur
face [c:\Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglCreateContext [c
:\Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglTerminate [c:\Us
ers\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
webgl.obj : error LNK2001: unresolved external symbol __imp_eglGetDisplay [c:\U
sers\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
procs.obj : error LNK2001: unresolved external symbol __imp_eglGetProcAddress [
c:\Users\dmitry\Dropbox\Projects\headless-gl\build\webgl.vcxproj]
c:\Users\dmitry\Dropbox\Projects\headless-gl\build\Release\webgl.node : fatal e
rror LNK1120: 9 unresolved externals [c:\Users\dmitry\Dropbox\Projects\headless
-gl\build\webgl.vcxproj]
```

**Comment by dfcreative** [comment]
[LNK2001](https://msdn.microsoft.com/en-us/library/f6xx1b1z.aspx) is a linker error of unresolved functions in [webgl.cc](https://github.com/stackgl/headless-gl/blob/master/src/webgl.cc#L91). It seems that linker cannot find [libEGL.cpp](https://github.com/mikolalysenko/angle/blob/39a008f01570fe2efda4affb43d22478251b6ab1/src/libEGL/libEGL.cpp) for [EGL/egl.h](https://github.com/stackgl/headless-gl/blob/master/src/webgl.h#L13).
Not sure what the reason of that, attempts to add `includes` or [`linker_inputs`](https://gyp.gsrc.io/docs/InputFormatReference.md#link_settings) did not bear fruits.
There is another way to use angle, described in [angle build instructions](https://github.com/google/angle/blob/master/doc/DevSetup.md#to-use-angle-in-your-application).
But following that I didn’t manage to compile the new version of [google/angle](https://github.com/google/angle). Their [angle.gyp](https://github.com/google/angle/blob/master/src/angle.gyp) file seems to be broken (no `angle_path` found). Making it include [`common.gypi`](https://github.com/google/angle/blob/master/build/common.gypi) gives compilation error.
Anyways I gave up efforts for now.

**Comment by mikolalysenko** [comment]
Unfortunately windows isn't supported yet.  I don't have access to a windows system so it is hard for me to do basic testing and building in that environment.

**Comment by mohamedmansour** [comment]
I tried as well and got the following error:

77 error Failed at the gl@2.1.5 install script 'prebuild --install'.
77 error Make sure you have the latest version of node.js and npm installed.
77 error If you do, this is most likely a problem with the gl package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     prebuild --install

**Comment by bpedrosa** [comment]
I've playing around with this and a possible easy fix to make it working on windows would be building angle as a shared library, just change the flag [here](https://github.com/mikolalysenko/angle/blob/0f4f64860e6faa655baef76eaeb69ab9fc3c20ec/src/angle.gyp#L32) to 'shared_library' and rebuild it `# npm install msvs_version=2013`

After that, the .node module will need to have access to libEGL.dll and libGLESv2.dll , so you can copy them in the Release folder.

It's not an optimal solution but at least it does allow you to use the library on windows.

Regards.

PS: Used msvs 2013 (x64) and node v5.8.0 (x64) over here

**Comment by mikolalysenko** [comment]
Seems to be working now.  While the CI badge for appveyor isn't updating the online builds are now working and all test cases are passing.  Going to close this issue.

**Comment by dfcreative** [comment]
Cant wait how happy i am going to be rendering sound with shaders in node!

**Comment by mikolalysenko** [comment]
Should have 64 bit prebuilds up once the appveyor build completes.
