### ISSUE TITLE
Extension support

### ISSUE THREAD

**Issue by mikolalysenko** [stackgl/headless-gl#5]
Need to verify that extension support from node-webgl is working.

**Comment by mikolalysenko** [comment]
No extensions implemented yet, but at least it doesn't crash.

**Comment by waylonflinn** [comment]
:+1: 

Need `OES_texture_float` support for my GPGPU library, [weblas](www.github.com/waylonflinn/weblas)

Hoping to use this to enable support for node.

**Comment by wellsjo** [comment]
does anyone have a workaround for this, or an idea of when this will be implemented?

**Comment by mikolalysenko** [comment]
ANGLE_instance_arrays is now implemented.

OES_texture_float is probably a good candidate for the next API.

**Comment by arose** [comment]
OES_element_index_uint would also be great!

**Comment by scashews** [comment]
Just curious if any extensions are implemented, because I need OES_standard_derivatives for normal mapping. I was thinking if some were implemented, basically if the structure is there, maybe I could figure out how to add support for this one. Thanks!

**Comment by scashews** [comment]
Well, interesting, it looks like it's supported in the shader despite the fact that it advertises that that extension is not supported.

**Comment by kylegmaxwell** [comment]
It would really help if common extensions used by Three.js were supported. Thanks
THREE.WebGLRenderer: TypeError: _canvas.addEventListener is not a function
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
THREE.WebGLRenderer: OES_texture_float extension not supported.
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
THREE.WebGLRenderer: OES_standard_derivatives extension not supported.
THREE.WebGLRenderer: OES_element_index_uint extension not supported.

**Comment by markkorput** [comment]
I'm trying (and failing) to render textures using headless-gl and three.js (see my [three.js forum post](https://discourse.threejs.org/t/server-side-node-js-browserless-texture-rendering/2717/1) for details on that).

I'm guessing it has something to do with the unsupported extensions that @kylegmaxwell mentioned, because I'm getting the same warnings in my log.

Are there any plans to implement these extensions?

**Comment by robin-rpr** [comment]
Two years later and still no `getExtension()` support in [webgl.cc](https://github.com/stackgl/headless-gl/blob/master/src/webgl.cc).  I'm disappointed.

**Comment by dhritzkiv** [comment]
Hi all, OES_texture_float and OES_element_index_uint should be supported in 4.1.1.

There were conformance issues with OES_standard_derivatives that prevented me from integrating it successfully.

**Comment by Aeium** [comment]
I am trying to get this to work:

https://bl.ocks.org/bsergean/6780d7cc0cabb1b4d6c8

THREE.WebGLRenderer 97
THREE.WebGLRenderer: _canvas.addEventListener is not a function
TypeError: Cannot read property 'getShaderPrecisionFormat' of undefined
    at getMaxPrecision (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\three\build\three.js:14818:13)
    at new WebGLCapabilities (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\three\build\three.js:14847:22)
    at initGLContext (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\three\build\three.js:22153:19)
    at new WebGLRenderer (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\three\build\three.js:22203:3)
    at Object.<anonymous> (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\offscreen_sample.coffee:34:12)
    at Object.<anonymous> (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\offscreen_sample.coffee:3:1)
    at Module._compile (module.js:653:30)
    at Object.exports.run (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\coffee-script\lib\coffee-script\coffee-script.js:173:23)
    at compileScript (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
    at compilePath (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
    at Object.exports.run (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
    at Object.<anonymous> (D:\offscreen-rendering\6780d7cc0cabb1b4d6c8\node_modules\coffee-script\bin\coffee:15:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Any ideas what to try?

**Comment by dhritzkiv** [comment]
I’m on the move now, but I believe you must pass height and width arguments to the gl/context invocation

**Comment by FrederikVanhollebeke** [comment]
Also a bit stuck when trying to run Three.js in node on a headless system. Same error here:
THREE.WebGLRenderer 104
THREE.WebGLRenderer: _canvas.addEventListener is not a function

Any idea how to proceed with this issue?

**Comment by dhritzkiv** [comment]
Hi. I'm unsure how you're choosing to make the canvas element available to your non DOM environment (there are many options on npm), but here's my super minimal way of shimming the canvas element for three.js:

```js
const noop = () => {};

global.addEventListener = noop;
global.HTMLImageElement = noop;
global.HTMLCanvasElement = noop;

class Canvas {
	constructor() {
		this.style = {};
	}

	addEventListener() {
		//noop
	}
}
```

and then when creating the renderer:

```js
const gl = createContext(width, height);
const canvas = new Canvas();

const renderer = new THREE.WebGLRenderer({
	context: gl,
	canvas
});
```

Ultimately, the canvas element is not important on the server, only the gl context. Unfortunately, three.js requires it by default

**Comment by FrederikVanhollebeke** [comment]
@dhritzkiv Thanks!!

**Comment by verina09** [comment]
> ```js
> noop
> ```

I wonder if we could use node-canvas instead of 'dummy' canvas element to get the render output? Has anyone tried? I tried but it is giving an empty canvas instead..

**Comment by dhritzkiv** [comment]
It's best to use the dummy canvas, as none of the features present in the dom's canvas (or node-canvas) are used by headless-gl. The dummy canvas is only required for libraries which assume a browser environment (e.g. three.js). Otherwise, the webgl context is backed by what is essentially a buffer.

You may even add `toDataURL` to your dummy canvas implementation, by wrapping some code around the gl context's buffer, but that is an exercise left up to you.

**Comment by verina09** [comment]
@dhritzkiv thankyou for your reply, will be exercising then 💪💪
