### ISSUE TITLE
Latest version broken on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by gi11es** [stackgl/headless-gl#56]
Installing the latest on Ubuntu 14.04 LTS, when trying to run code that uses headless-gl I get:

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/3d2png/node_modules/gl/build/Release/webgl.node)

This doesn't happen with 2.1.5

**Comment by mikolalysenko** [comment]
That is annoying. Does this problem happen if you build headless-gl from source, or is it just with the prebuilt binaries?

**Comment by mikolalysenko** [comment]
Also what version of node are you using?

**Comment by gi11es** [comment]
vagrant@mediawiki-vagrant:/var/3d2png$ node --version
v4.4.2

I just define gl as a dependency to my project in package.json and run npm install from there. I'm new to node, I don't know if that builds from source or not.

**Comment by mikolalysenko** [comment]
It is probably using a prebuilt binary then.  For now if you can just use 2.1.5.  I'll try to dig into this issue more this weekend.

**Comment by mikolalysenko** [comment]
Try it now, there is a good chance that it should be fixed.   I built the newest version against the default gcc instead of 4.9, which may have solved the problem.

**Comment by gi11es** [comment]
Indeed, it works fine now pointing to latest (3.0.5). Thank you!
