### ISSUE TITLE
is gl.UNPACK_FLIP_Y_WEBGL supported?

### ISSUE THREAD

**Issue by makc** [stackgl/headless-gl#57]
it seems gl.pixelStorei (gl.UNPACK_FLIP_Y_WEBGL, ...) does not have any effect.

**Comment by mikolalysenko** [comment]
It should be supported, this might be a bug.  Can you add a test case?

**Comment by makc** [comment]
I tried this with three.js, so I cannot be entirely sure the problem is with headless-gl, actually. they have `flipY` on textures and [this line](https://github.com/mrdoob/three.js/blob/cf584a60bdfd24c42eaa81d484533364742bda44/src/renderers/WebGLRenderer.js#L2867) should be calling pixelStorei based on that, but who knows...

**Comment by makc** [comment]
nvm, I just tried again, and it works. must be a typo.
