### ISSUE TITLE
compile fails on ubuntu

### ISSUE THREAD

**Issue by gedw99** [stackgl/headless-gl#6]
running in virtualbox with 3d acceleration setup

gedw@gedw-VirtualBox:~/_data/headlesswebgl$ ls
gedw@gedw-VirtualBox:~/_data/headlesswebgl$ npm install gl
npm http GET https://registry.npmjs.org/gl
npm http 200 https://registry.npmjs.org/gl
npm http GET https://registry.npmjs.org/gl/-/gl-0.0.2.tgz
npm http 200 https://registry.npmjs.org/gl/-/gl-0.0.2.tgz

> gl@0.0.2 install /home/gedw/_data/headlesswebgl/node_modules/gl
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.13/node-v0.10.13.tar.gz
make: Entering directory `/home/gedw/_data/headlesswebgl/node_modules/gl/build'
  CXX(target) Release/obj.target/webgl/src/bindings.o
In file included from ../src/bindings.cc:15:0:
../src/webgl.h:32:3: error: ‘GLuint’ does not name a type
../src/webgl.h:33:28: error: ‘GLuint’ has not been declared
../src/webgl.h: In constructor ‘GLObj::GLObj(GLObjectType, int)’:
../src/webgl.h:35:11: error: ‘struct GLObj’ has no member named ‘obj’
../src/webgl.h: At global scope:
../src/webgl.h:45:3: error: ‘GL_CONTEXT_TYPE’ does not name a type
../src/webgl.h:48:41: error: ‘GLuint’ has not been declared
../src/webgl.h:49:24: error: ‘GLuint’ has not been declared
../src/bindings.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/bindings.cc:187:3: error: ‘GL_DEPTH_BUFFER_BIT’ was not declared in this scope
../src/bindings.cc:188:3: error: ‘GL_STENCIL_BUFFER_BIT’ was not declared in this scope
../src/bindings.cc:189:3: error: ‘GL_COLOR_BUFFER_BIT’ was not declared in this scope
../src/bindings.cc:192:3: error: ‘GL_FALSE’ was not declared in this scope
../src/bindings.cc:193:3: error: ‘GL_TRUE’ was not declared in this scope
../src/bindings.cc:196:3: error: ‘GL_POINTS’ was not declared in this scope
../src/bindings.cc:197:3: error: ‘GL_LINES’ was not declared in this scope
../src/bindings.cc:198:3: error: ‘GL_LINE_LOOP’ was not declared in this scope
../src/bindings.cc:199:3: error: ‘GL_LINE_STRIP’ was not declared in this scope
../src/bindings.cc:200:3: error: ‘GL_TRIANGLES’ was not declared in this scope
../src/bindings.cc:201:3: error: ‘GL_TRIANGLE_STRIP’ was not declared in this scope
../src/bindings.cc:202:3: error: ‘GL_TRIANGLE_FAN’ was not declared in this scope
../src/bindings.cc:215:3: error: ‘GL_ZERO’ was not declared in this scope
../src/bindings.cc:216:3: error: ‘GL_ONE’ was not declared in this scope
../src/bindings.cc:217:3: error: ‘GL_SRC_COLOR’ was not declared in this scope
../src/bindings.cc:218:3: error: ‘GL_ONE_MINUS_SRC_COLOR’ was not declared in this scope
../src/bindings.cc:219:3: error: ‘GL_SRC_ALPHA’ was not declared in this scope
../src/bindings.cc:220:3: error: ‘GL_ONE_MINUS_SRC_ALPHA’ was not declared in this scope
../src/bindings.cc:221:3: error: ‘GL_DST_ALPHA’ was not declared in this scope
../src/bindings.cc:222:3: error: ‘GL_ONE_MINUS_DST_ALPHA’ was not declared in this scope
../src/bindings.cc:227:3: error: ‘GL_DST_COLOR’ was not declared in this scope
../src/bindings.cc:228:3: error: ‘GL_ONE_MINUS_DST_COLOR’ was not declared in this scope
../src/bindings.cc:229:3: error: ‘GL_SRC_ALPHA_SATURATE’ was not declared in this scope
../src/bindings.cc:236:3: error: ‘GL_FUNC_ADD’ was not declared in this scope
../src/bindings.cc:237:3: error: ‘GL_BLEND_EQUATION’ was not declared in this scope
../src/bindings.cc:238:3: error: ‘GL_BLEND_EQUATION_RGB’ was not declared in this scope
../src/bindings.cc:239:3: error: ‘GL_BLEND_EQUATION_ALPHA’ was not declared in this scope
../src/bindings.cc:242:3: error: ‘GL_FUNC_SUBTRACT’ was not declared in this scope
../src/bindings.cc:243:3: error: ‘GL_FUNC_REVERSE_SUBTRACT’ was not declared in this scope
../src/bindings.cc:246:3: error: ‘GL_BLEND_DST_RGB’ was not declared in this scope
../src/bindings.cc:247:3: error: ‘GL_BLEND_SRC_RGB’ was not declared in this scope
../src/bindings.cc:248:3: error: ‘GL_BLEND_DST_ALPHA’ was not declared in this scope
../src/bindings.cc:249:3: error: ‘GL_BLEND_SRC_ALPHA’ was not declared in this scope
../src/bindings.cc:250:3: error: ‘GL_CONSTANT_COLOR’ was not declared in this scope
../src/bindings.cc:251:3: error: ‘GL_ONE_MINUS_CONSTANT_COLOR’ was not declared in this scope
../src/bindings.cc:252:3: error: ‘GL_CONSTANT_ALPHA’ was not declared in this scope
../src/bindings.cc:253:3: error: ‘GL_ONE_MINUS_CONSTANT_ALPHA’ was not declared in this scope
../src/bindings.cc:254:3: error: ‘GL_BLEND_COLOR’ was not declared in this scope
../src/bindings.cc:257:3: error: ‘GL_ARRAY_BUFFER’ was not declared in this scope
../src/bindings.cc:258:3: error: ‘GL_ELEMENT_ARRAY_BUFFER’ was not declared in this scope
../src/bindings.cc:259:3: error: ‘GL_ARRAY_BUFFER_BINDING’ was not declared in this scope
../src/bindings.cc:260:3: error: ‘GL_ELEMENT_ARRAY_BUFFER_BINDING’ was not declared in this scope
../src/bindings.cc:262:3: error: ‘GL_STREAM_DRAW’ was not declared in this scope
../src/bindings.cc:263:3: error: ‘GL_STATIC_DRAW’ was not declared in this scope
../src/bindings.cc:264:3: error: ‘GL_DYNAMIC_DRAW’ was not declared in this scope
../src/bindings.cc:266:3: error: ‘GL_BUFFER_SIZE’ was not declared in this scope
../src/bindings.cc:267:3: error: ‘GL_BUFFER_USAGE’ was not declared in this scope
../src/bindings.cc:269:3: error: ‘GL_CURRENT_VERTEX_ATTRIB’ was not declared in this scope
../src/bindings.cc:272:3: error: ‘GL_FRONT’ was not declared in this scope
../src/bindings.cc:273:3: error: ‘GL_BACK’ was not declared in this scope
../src/bindings.cc:274:3: error: ‘GL_FRONT_AND_BACK’ was not declared in this scope
../src/bindings.cc:287:3: error: ‘GL_TEXTURE_2D’ was not declared in this scope
../src/bindings.cc:288:3: error: ‘GL_CULL_FACE’ was not declared in this scope
../src/bindings.cc:289:3: error: ‘GL_BLEND’ was not declared in this scope
../src/bindings.cc:290:3: error: ‘GL_DITHER’ was not declared in this scope
../src/bindings.cc:291:3: error: ‘GL_STENCIL_TEST’ was not declared in this scope
../src/bindings.cc:292:3: error: ‘GL_DEPTH_TEST’ was not declared in this scope
../src/bindings.cc:293:3: error: ‘GL_SCISSOR_TEST’ was not declared in this scope
../src/bindings.cc:294:3: error: ‘GL_POLYGON_OFFSET_FILL’ was not declared in this scope
../src/bindings.cc:295:3: error: ‘GL_SAMPLE_ALPHA_TO_COVERAGE’ was not declared in this scope
../src/bindings.cc:296:3: error: ‘GL_SAMPLE_COVERAGE’ was not declared in this scope
../src/bindings.cc:299:3: error: ‘GL_NO_ERROR’ was not declared in this scope
../src/bindings.cc:300:3: error: ‘GL_INVALID_ENUM’ was not declared in this scope
../src/bindings.cc:301:3: error: ‘GL_INVALID_VALUE’ was not declared in this scope
../src/bindings.cc:302:3: error: ‘GL_INVALID_OPERATION’ was not declared in this scope
../src/bindings.cc:303:3: error: ‘GL_OUT_OF_MEMORY’ was not declared in this scope
../src/bindings.cc:306:3: error: ‘GL_CW’ was not declared in this scope
../src/bindings.cc:307:3: error: ‘GL_CCW’ was not declared in this scope
../src/bindings.cc:310:3: error: ‘GL_LINE_WIDTH’ was not declared in this scope
../src/bindings.cc:311:3: error: ‘GL_ALIASED_POINT_SIZE_RANGE’ was not declared in this scope
../src/bindings.cc:312:3: error: ‘GL_ALIASED_LINE_WIDTH_RANGE’ was not declared in this scope
../src/bindings.cc:313:3: error: ‘GL_CULL_FACE_MODE’ was not declared in this scope
../src/bindings.cc:314:3: error: ‘GL_FRONT_FACE’ was not declared in this scope
../src/bindings.cc:315:3: error: ‘GL_DEPTH_RANGE’ was not declared in this scope
../src/bindings.cc:316:3: error: ‘GL_DEPTH_WRITEMASK’ was not declared in this scope
../src/bindings.cc:317:3: error: ‘GL_DEPTH_CLEAR_VALUE’ was not declared in this scope
../src/bindings.cc:318:3: error: ‘GL_DEPTH_FUNC’ was not declared in this scope
../src/bindings.cc:319:3: error: ‘GL_STENCIL_CLEAR_VALUE’ was not declared in this scope
../src/bindings.cc:320:3: error: ‘GL_STENCIL_FUNC’ was not declared in this scope
../src/bindings.cc:321:3: error: ‘GL_STENCIL_FAIL’ was not declared in this scope
../src/bindings.cc:322:3: error: ‘GL_STENCIL_PASS_DEPTH_FAIL’ was not declared in this scope
../src/bindings.cc:323:3: error: ‘GL_STENCIL_PASS_DEPTH_PASS’ was not declared in this scope
../src/bindings.cc:324:3: error: ‘GL_STENCIL_REF’ was not declared in this scope
../src/bindings.cc:325:3: error: ‘GL_STENCIL_VALUE_MASK’ was not declared in this scope
../src/bindings.cc:326:3: error: ‘GL_STENCIL_WRITEMASK’ was not declared in this scope
../src/bindings.cc:327:3: error: ‘GL_STENCIL_BACK_FUNC’ was not declared in this scope
../src/bindings.cc:328:3: error: ‘GL_STENCIL_BACK_FAIL’ was not declared in this scope
../src/bindings.cc:329:3: error: ‘GL_STENCIL_BACK_PASS_DEPTH_FAIL’ was not declared in this scope
../src/bindings.cc:330:3: error: ‘GL_STENCIL_BACK_PASS_DEPTH_PASS’ was not declared in this scope
../src/bindings.cc:331:3: error: ‘GL_STENCIL_BACK_REF’ was not declared in this scope
../src/bindings.cc:332:3: error: ‘GL_STENCIL_BACK_VALUE_MASK’ was not declared in this scope
../src/bindings.cc:333:3: error: ‘GL_STENCIL_BACK_WRITEMASK’ was not declared in this scope
../src/bindings.cc:334:3: error: ‘GL_VIEWPORT’ was not declared in this scope
../src/bindings.cc:335:3: error: ‘GL_SCISSOR_BOX’ was not declared in this scope
../src/bindings.cc:337:3: error: ‘GL_COLOR_CLEAR_VALUE’ was not declared in this scope
../src/bindings.cc:338:3: error: ‘GL_COLOR_WRITEMASK’ was not declared in this scope
../src/bindings.cc:339:3: error: ‘GL_UNPACK_ALIGNMENT’ was not declared in this scope
../src/bindings.cc:340:3: error: ‘GL_PACK_ALIGNMENT’ was not declared in this scope
../src/bindings.cc:341:3: error: ‘GL_MAX_TEXTURE_SIZE’ was not declared in this scope
../src/bindings.cc:342:3: error: ‘GL_MAX_VIEWPORT_DIMS’ was not declared in this scope
../src/bindings.cc:343:3: error: ‘GL_SUBPIXEL_BITS’ was not declared in this scope
../src/bindings.cc:344:3: error: ‘GL_RED_BITS’ was not declared in this scope
../src/bindings.cc:345:3: error: ‘GL_GREEN_BITS’ was not declared in this scope
../src/bindings.cc:346:3: error: ‘GL_BLUE_BITS’ was not declared in this scope
../src/bindings.cc:347:3: error: ‘GL_ALPHA_BITS’ was not declared in this scope
../src/bindings.cc:348:3: error: ‘GL_DEPTH_BITS’ was not declared in this scope
../src/bindings.cc:349:3: error: ‘GL_STENCIL_BITS’ was not declared in this scope
../src/bindings.cc:350:3: error: ‘GL_POLYGON_OFFSET_UNITS’ was not declared in this scope
../src/bindings.cc:352:3: error: ‘GL_POLYGON_OFFSET_FACTOR’ was not declared in this scope
../src/bindings.cc:353:3: error: ‘GL_TEXTURE_BINDING_2D’ was not declared in this scope
../src/bindings.cc:354:3: error: ‘GL_SAMPLE_BUFFERS’ was not declared in this scope
../src/bindings.cc:355:3: error: ‘GL_SAMPLES’ was not declared in this scope
../src/bindings.cc:356:3: error: ‘GL_SAMPLE_COVERAGE_VALUE’ was not declared in this scope
../src/bindings.cc:357:3: error: ‘GL_SAMPLE_COVERAGE_INVERT’ was not declared in this scope
../src/bindings.cc:365:3: error: ‘GL_NUM_COMPRESSED_TEXTURE_FORMATS’ was not declared in this scope
../src/bindings.cc:366:3: error: ‘GL_COMPRESSED_TEXTURE_FORMATS’ was not declared in this scope
../src/bindings.cc:369:3: error: ‘GL_DONT_CARE’ was not declared in this scope
../src/bindings.cc:370:3: error: ‘GL_FASTEST’ was not declared in this scope
../src/bindings.cc:371:3: error: ‘GL_NICEST’ was not declared in this scope
../src/bindings.cc:374:3: error: ‘GL_GENERATE_MIPMAP_HINT’ was not declared in this scope
../src/bindings.cc:377:3: error: ‘GL_BYTE’ was not declared in this scope
../src/bindings.cc:378:3: error: ‘GL_UNSIGNED_BYTE’ was not declared in this scope
../src/bindings.cc:379:3: error: ‘GL_SHORT’ was not declared in this scope
../src/bindings.cc:380:3: error: ‘GL_UNSIGNED_SHORT’ was not declared in this scope
../src/bindings.cc:381:3: error: ‘GL_INT’ was not declared in this scope
../src/bindings.cc:382:3: error: ‘GL_UNSIGNED_INT’ was not declared in this scope
../src/bindings.cc:383:3: error: ‘GL_FLOAT’ was not declared in this scope
../src/bindings.cc:385:3: error: ‘GL_FIXED’ was not declared in this scope
../src/bindings.cc:389:3: error: ‘GL_DEPTH_COMPONENT’ was not declared in this scope
../src/bindings.cc:390:3: error: ‘GL_ALPHA’ was not declared in this scope
../src/bindings.cc:391:3: error: ‘GL_RGB’ was not declared in this scope
../src/bindings.cc:392:3: error: ‘GL_RGBA’ was not declared in this scope
../src/bindings.cc:393:3: error: ‘GL_LUMINANCE’ was not declared in this scope
../src/bindings.cc:394:3: error: ‘GL_LUMINANCE_ALPHA’ was not declared in this scope
../src/bindings.cc:398:3: error: ‘GL_UNSIGNED_SHORT_4_4_4_4’ was not declared in this scope
../src/bindings.cc:399:3: error: ‘GL_UNSIGNED_SHORT_5_5_5_1’ was not declared in this scope
../src/bindings.cc:400:3: error: ‘GL_UNSIGNED_SHORT_5_6_5’ was not declared in this scope
../src/bindings.cc:403:3: error: ‘GL_FRAGMENT_SHADER’ was not declared in this scope
../src/bindings.cc:404:3: error: ‘GL_VERTEX_SHADER’ was not declared in this scope
../src/bindings.cc:405:3: error: ‘GL_MAX_VERTEX_ATTRIBS’ was not declared in this scope
../src/bindings.cc:407:3: error: ‘GL_MAX_VERTEX_UNIFORM_VECTORS’ was not declared in this scope
../src/bindings.cc:408:3: error: ‘GL_MAX_VARYING_VECTORS’ was not declared in this scope
../src/bindings.cc:410:3: error: ‘GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS’ was not declared in this scope
../src/bindings.cc:411:3: error: ‘GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS’ was not declared in this scope
../src/bindings.cc:412:3: error: ‘GL_MAX_TEXTURE_IMAGE_UNITS’ was not declared in this scope
../src/bindings.cc:414:3: error: ‘GL_MAX_FRAGMENT_UNIFORM_VECTORS’ was not declared in this scope
../src/bindings.cc:416:3: error: ‘GL_SHADER_TYPE’ was not declared in this scope
../src/bindings.cc:417:3: error: ‘GL_DELETE_STATUS’ was not declared in this scope
../src/bindings.cc:418:3: error: ‘GL_LINK_STATUS’ was not declared in this scope
../src/bindings.cc:419:3: error: ‘GL_VALIDATE_STATUS’ was not declared in this scope
../src/bindings.cc:420:3: error: ‘GL_ATTACHED_SHADERS’ was not declared in this scope
../src/bindings.cc:421:3: error: ‘GL_ACTIVE_UNIFORMS’ was not declared in this scope
../src/bindings.cc:422:3: error: ‘GL_ACTIVE_UNIFORM_MAX_LENGTH’ was not declared in this scope
../src/bindings.cc:423:3: error: ‘GL_ACTIVE_ATTRIBUTES’ was not declared in this scope
../src/bindings.cc:424:3: error: ‘GL_ACTIVE_ATTRIBUTE_MAX_LENGTH’ was not declared in this scope
../src/bindings.cc:425:3: error: ‘GL_SHADING_LANGUAGE_VERSION’ was not declared in this scope
../src/bindings.cc:426:3: error: ‘GL_CURRENT_PROGRAM’ was not declared in this scope
../src/bindings.cc:429:3: error: ‘GL_NEVER’ was not declared in this scope
../src/bindings.cc:430:3: error: ‘GL_LESS’ was not declared in this scope
../src/bindings.cc:431:3: error: ‘GL_EQUAL’ was not declared in this scope
../src/bindings.cc:432:3: error: ‘GL_LEQUAL’ was not declared in this scope
../src/bindings.cc:433:3: error: ‘GL_GREATER’ was not declared in this scope
../src/bindings.cc:434:3: error: ‘GL_NOTEQUAL’ was not declared in this scope
../src/bindings.cc:435:3: error: ‘GL_GEQUAL’ was not declared in this scope
../src/bindings.cc:436:3: error: ‘GL_ALWAYS’ was not declared in this scope
../src/bindings.cc:440:3: error: ‘GL_KEEP’ was not declared in this scope
../src/bindings.cc:441:3: error: ‘GL_REPLACE’ was not declared in this scope
../src/bindings.cc:442:3: error: ‘GL_INCR’ was not declared in this scope
../src/bindings.cc:443:3: error: ‘GL_DECR’ was not declared in this scope
../src/bindings.cc:444:3: error: ‘GL_INVERT’ was not declared in this scope
../src/bindings.cc:445:3: error: ‘GL_INCR_WRAP’ was not declared in this scope
../src/bindings.cc:446:3: error: ‘GL_DECR_WRAP’ was not declared in this scope
../src/bindings.cc:449:3: error: ‘GL_VENDOR’ was not declared in this scope
../src/bindings.cc:450:3: error: ‘GL_RENDERER’ was not declared in this scope
../src/bindings.cc:451:3: error: ‘GL_VERSION’ was not declared in this scope
../src/bindings.cc:452:3: error: ‘GL_EXTENSIONS’ was not declared in this scope
../src/bindings.cc:455:3: error: ‘GL_NEAREST’ was not declared in this scope
../src/bindings.cc:456:3: error: ‘GL_LINEAR’ was not declared in this scope
../src/bindings.cc:461:3: error: ‘GL_NEAREST_MIPMAP_NEAREST’ was not declared in this scope
../src/bindings.cc:462:3: error: ‘GL_LINEAR_MIPMAP_NEAREST’ was not declared in this scope
../src/bindings.cc:463:3: error: ‘GL_NEAREST_MIPMAP_LINEAR’ was not declared in this scope
../src/bindings.cc:464:3: error: ‘GL_LINEAR_MIPMAP_LINEAR’ was not declared in this scope
../src/bindings.cc:467:3: error: ‘GL_TEXTURE_MAG_FILTER’ was not declared in this scope
../src/bindings.cc:468:3: error: ‘GL_TEXTURE_MIN_FILTER’ was not declared in this scope
../src/bindings.cc:469:3: error: ‘GL_TEXTURE_WRAP_S’ was not declared in this scope
../src/bindings.cc:470:3: error: ‘GL_TEXTURE_WRAP_T’ was not declared in this scope
../src/bindings.cc:474:3: error: ‘GL_TEXTURE’ was not declared in this scope
../src/bindings.cc:476:3: error: ‘GL_TEXTURE_CUBE_MAP’ was not declared in this scope
../src/bindings.cc:477:3: error: ‘GL_TEXTURE_BINDING_CUBE_MAP’ was not declared in this scope
../src/bindings.cc:478:3: error: ‘GL_TEXTURE_CUBE_MAP_POSITIVE_X’ was not declared in this scope
../src/bindings.cc:479:3: error: ‘GL_TEXTURE_CUBE_MAP_NEGATIVE_X’ was not declared in this scope
../src/bindings.cc:480:3: error: ‘GL_TEXTURE_CUBE_MAP_POSITIVE_Y’ was not declared in this scope
../src/bindings.cc:481:3: error: ‘GL_TEXTURE_CUBE_MAP_NEGATIVE_Y’ was not declared in this scope
../src/bindings.cc:482:3: error: ‘GL_TEXTURE_CUBE_MAP_POSITIVE_Z’ was not declared in this scope
../src/bindings.cc:483:3: error: ‘GL_TEXTURE_CUBE_MAP_NEGATIVE_Z’ was not declared in this scope
../src/bindings.cc:484:3: error: ‘GL_MAX_CUBE_MAP_TEXTURE_SIZE’ was not declared in this scope
../src/bindings.cc:487:3: error: ‘GL_TEXTURE0’ was not declared in this scope
../src/bindings.cc:488:3: error: ‘GL_TEXTURE1’ was not declared in this scope
../src/bindings.cc:489:3: error: ‘GL_TEXTURE2’ was not declared in this scope
../src/bindings.cc:490:3: error: ‘GL_TEXTURE3’ was not declared in this scope
../src/bindings.cc:491:3: error: ‘GL_TEXTURE4’ was not declared in this scope
../src/bindings.cc:492:3: error: ‘GL_TEXTURE5’ was not declared in this scope
../src/bindings.cc:493:3: error: ‘GL_TEXTURE6’ was not declared in this scope
../src/bindings.cc:494:3: error: ‘GL_TEXTURE7’ was not declared in this scope
../src/bindings.cc:495:3: error: ‘GL_TEXTURE8’ was not declared in this scope
../src/bindings.cc:496:3: error: ‘GL_TEXTURE9’ was not declared in this scope
../src/bindings.cc:497:3: error: ‘GL_TEXTURE10’ was not declared in this scope
../src/bindings.cc:498:3: error: ‘GL_TEXTURE11’ was not declared in this scope
../src/bindings.cc:499:3: error: ‘GL_TEXTURE12’ was not declared in this scope
../src/bindings.cc:500:3: error: ‘GL_TEXTURE13’ was not declared in this scope
../src/bindings.cc:501:3: error: ‘GL_TEXTURE14’ was not declared in this scope
../src/bindings.cc:502:3: error: ‘GL_TEXTURE15’ was not declared in this scope
../src/bindings.cc:503:3: error: ‘GL_TEXTURE16’ was not declared in this scope
../src/bindings.cc:504:3: error: ‘GL_TEXTURE17’ was not declared in this scope
../src/bindings.cc:505:3: error: ‘GL_TEXTURE18’ was not declared in this scope
../src/bindings.cc:506:3: error: ‘GL_TEXTURE19’ was not declared in this scope
../src/bindings.cc:507:3: error: ‘GL_TEXTURE20’ was not declared in this scope
../src/bindings.cc:508:3: error: ‘GL_TEXTURE21’ was not declared in this scope
../src/bindings.cc:509:3: error: ‘GL_TEXTURE22’ was not declared in this scope
../src/bindings.cc:510:3: error: ‘GL_TEXTURE23’ was not declared in this scope
../src/bindings.cc:511:3: error: ‘GL_TEXTURE24’ was not declared in this scope
../src/bindings.cc:512:3: error: ‘GL_TEXTURE25’ was not declared in this scope
../src/bindings.cc:513:3: error: ‘GL_TEXTURE26’ was not declared in this scope
../src/bindings.cc:514:3: error: ‘GL_TEXTURE27’ was not declared in this scope
../src/bindings.cc:515:3: error: ‘GL_TEXTURE28’ was not declared in this scope
../src/bindings.cc:516:3: error: ‘GL_TEXTURE29’ was not declared in this scope
../src/bindings.cc:517:3: error: ‘GL_TEXTURE30’ was not declared in this scope
../src/bindings.cc:518:3: error: ‘GL_TEXTURE31’ was not declared in this scope
../src/bindings.cc:519:3: error: ‘GL_ACTIVE_TEXTURE’ was not declared in this scope
../src/bindings.cc:522:3: error: ‘GL_REPEAT’ was not declared in this scope
../src/bindings.cc:523:3: error: ‘GL_CLAMP_TO_EDGE’ was not declared in this scope
../src/bindings.cc:524:3: error: ‘GL_MIRRORED_REPEAT’ was not declared in this scope
../src/bindings.cc:527:3: error: ‘GL_FLOAT_VEC2’ was not declared in this scope
../src/bindings.cc:528:3: error: ‘GL_FLOAT_VEC3’ was not declared in this scope
../src/bindings.cc:529:3: error: ‘GL_FLOAT_VEC4’ was not declared in this scope
../src/bindings.cc:530:3: error: ‘GL_INT_VEC2’ was not declared in this scope
../src/bindings.cc:531:3: error: ‘GL_INT_VEC3’ was not declared in this scope
../src/bindings.cc:532:3: error: ‘GL_INT_VEC4’ was not declared in this scope
../src/bindings.cc:533:3: error: ‘GL_BOOL’ was not declared in this scope
../src/bindings.cc:534:3: error: ‘GL_BOOL_VEC2’ was not declared in this scope
../src/bindings.cc:535:3: error: ‘GL_BOOL_VEC3’ was not declared in this scope
../src/bindings.cc:536:3: error: ‘GL_BOOL_VEC4’ was not declared in this scope
../src/bindings.cc:537:3: error: ‘GL_FLOAT_MAT2’ was not declared in this scope
../src/bindings.cc:538:3: error: ‘GL_FLOAT_MAT3’ was not declared in this scope
../src/bindings.cc:539:3: error: ‘GL_FLOAT_MAT4’ was not declared in this scope
../src/bindings.cc:540:3: error: ‘GL_SAMPLER_2D’ was not declared in this scope
../src/bindings.cc:541:3: error: ‘GL_SAMPLER_CUBE’ was not declared in this scope
../src/bindings.cc:544:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_ENABLED’ was not declared in this scope
../src/bindings.cc:545:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_SIZE’ was not declared in this scope
../src/bindings.cc:546:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_STRIDE’ was not declared in this scope
../src/bindings.cc:547:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_TYPE’ was not declared in this scope
../src/bindings.cc:548:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_NORMALIZED’ was not declared in this scope
../src/bindings.cc:549:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_POINTER’ was not declared in this scope
../src/bindings.cc:550:3: error: ‘GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING’ was not declared in this scope
../src/bindings.cc:554:3: error: ‘GL_IMPLEMENTATION_COLOR_READ_TYPE’ was not declared in this scope
../src/bindings.cc:555:3: error: ‘GL_IMPLEMENTATION_COLOR_READ_FORMAT’ was not declared in this scope
../src/bindings.cc:559:3: error: ‘GL_COMPILE_STATUS’ was not declared in this scope
../src/bindings.cc:560:3: error: ‘GL_INFO_LOG_LENGTH’ was not declared in this scope
../src/bindings.cc:561:3: error: ‘GL_SHADER_SOURCE_LENGTH’ was not declared in this scope
../src/bindings.cc:563:3: error: ‘GL_SHADER_COMPILER’ was not declared in this scope
../src/bindings.cc:568:3: error: ‘GL_SHADER_BINARY_FORMATS’ was not declared in this scope
../src/bindings.cc:569:3: error: ‘GL_NUM_SHADER_BINARY_FORMATS’ was not declared in this scope
../src/bindings.cc:574:3: error: ‘GL_LOW_FLOAT’ was not declared in this scope
../src/bindings.cc:575:3: error: ‘GL_MEDIUM_FLOAT’ was not declared in this scope
../src/bindings.cc:576:3: error: ‘GL_HIGH_FLOAT’ was not declared in this scope
../src/bindings.cc:577:3: error: ‘GL_LOW_INT’ was not declared in this scope
../src/bindings.cc:578:3: error: ‘GL_MEDIUM_INT’ was not declared in this scope
../src/bindings.cc:579:3: error: ‘GL_HIGH_INT’ was not declared in this scope
../src/bindings.cc:583:3: error: ‘GL_FRAMEBUFFER’ was not declared in this scope
../src/bindings.cc:584:3: error: ‘GL_RENDERBUFFER’ was not declared in this scope
../src/bindings.cc:586:3: error: ‘GL_RGBA4’ was not declared in this scope
../src/bindings.cc:587:3: error: ‘GL_RGB5_A1’ was not declared in this scope
../src/bindings.cc:591:3: error: ‘GL_DEPTH_COMPONENT16’ was not declared in this scope
../src/bindings.cc:592:3: error: ‘GL_STENCIL_INDEX’ was not declared in this scope
../src/bindings.cc:593:3: error: ‘GL_STENCIL_INDEX8’ was not declared in this scope
../src/bindings.cc:595:3: error: ‘GL_RENDERBUFFER_WIDTH’ was not declared in this scope
../src/bindings.cc:596:3: error: ‘GL_RENDERBUFFER_HEIGHT’ was not declared in this scope
../src/bindings.cc:597:3: error: ‘GL_RENDERBUFFER_INTERNAL_FORMAT’ was not declared in this scope
../src/bindings.cc:598:3: error: ‘GL_RENDERBUFFER_RED_SIZE’ was not declared in this scope
../src/bindings.cc:599:3: error: ‘GL_RENDERBUFFER_GREEN_SIZE’ was not declared in this scope
../src/bindings.cc:600:3: error: ‘GL_RENDERBUFFER_BLUE_SIZE’ was not declared in this scope
../src/bindings.cc:601:3: error: ‘GL_RENDERBUFFER_ALPHA_SIZE’ was not declared in this scope
../src/bindings.cc:602:3: error: ‘GL_RENDERBUFFER_DEPTH_SIZE’ was not declared in this scope
../src/bindings.cc:603:3: error: ‘GL_RENDERBUFFER_STENCIL_SIZE’ was not declared in this scope
../src/bindings.cc:605:3: error: ‘GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE’ was not declared in this scope
../src/bindings.cc:606:3: error: ‘GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME’ was not declared in this scope
../src/bindings.cc:607:3: error: ‘GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL’ was not declared in this scope
../src/bindings.cc:608:3: error: ‘GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE’ was not declared in this scope
../src/bindings.cc:610:3: error: ‘GL_COLOR_ATTACHMENT0’ was not declared in this scope
../src/bindings.cc:611:3: error: ‘GL_DEPTH_ATTACHMENT’ was not declared in this scope
../src/bindings.cc:612:3: error: ‘GL_STENCIL_ATTACHMENT’ was not declared in this scope
../src/bindings.cc:614:3: error: ‘GL_NONE’ was not declared in this scope
../src/bindings.cc:616:3: error: ‘GL_FRAMEBUFFER_COMPLETE’ was not declared in this scope
../src/bindings.cc:617:3: error: ‘GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT’ was not declared in this scope
../src/bindings.cc:618:3: error: ‘GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT’ was not declared in this scope
../src/bindings.cc:622:3: error: ‘GL_FRAMEBUFFER_UNSUPPORTED’ was not declared in this scope
../src/bindings.cc:624:3: error: ‘GL_FRAMEBUFFER_BINDING’ was not declared in this scope
../src/bindings.cc:625:3: error: ‘GL_RENDERBUFFER_BINDING’ was not declared in this scope
../src/bindings.cc:626:3: error: ‘GL_MAX_RENDERBUFFER_SIZE’ was not declared in this scope
../src/bindings.cc:628:3: error: ‘GL_INVALID_FRAMEBUFFER_OPERATION’ was not declared in this scope
make: *** [Release/obj.target/webgl/src/bindings.o] Error 1
make: Leaving directory `/home/gedw/_data/headlesswebgl/node_modules/gl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.5.0-36-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gedw/_data/headlesswebgl/node_modules/gl
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok 
unbuild gl@0.0.2
npm ERR! weird error 1
npm ERR! not ok code 0
gedw@gedw-VirtualBox:~/_data/headlesswebgl$ ^C
gedw@gedw-VirtualBox:~/_data/headlesswebgl$

**Comment by mikolalysenko** [comment]
Should be fixed in gl@2.0.0
