### ISSUE TITLE
On windows, npm package canot install

### ISSUE THREAD

**Issue by m2wasabi** [stackgl/headless-gl#60]
The command `npm install gl ` fails on windows.
However, old version `npm install gi@3.0.3` can success.

Following npm archived package not included `deps/windows/` directory.
https://registry.npmjs.org/gl/-/gl-3.0.5.tgz
I tried download this archive and add `deps/windows/` directory from git repository, npm install  has succeed.

**Comment by mikolalysenko** [comment]
I took these out temporarily from the npm distribution, and I guess this broke win32.  I don't have a windows machine, so I can't test it out locally.  I just pushed a new version that added them back in.  Let me know if this solves your problem.

**Comment by m2wasabi** [comment]
Thank you, mikolalysenko! It's good!

I using 3.0.6, and `npm install` succeed on windows.
It can be built on Appveyor successful.
Affected `deps/windows/*/x64`, node.js should be 64bit version.

Then, I updated `appveyor.yml` , and made a pull request.
https://github.com/stackgl/headless-gl/pull/61
