### ISSUE TITLE
Additive blend mode is broken

### ISSUE THREAD

**Issue by bhouston** [stackgl/headless-gl#62]
Hi guys!  Great project.  We are using it for http://clara.io.

I just wanted to share that we have determined conclusively that the additive pre-multiplied blend mode is incorrect in headless-gl.

Specifically this does not work:
```
gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
gl.blendFuncSeparate( gl.ONE, gl.ONE, gl.ONE, gl.ONE );
```

The above should be functionally equivalent to:
```
gl_FragColor.rgb = src.rgb + dst.rgb;
gl_FragColor.a = src.a + dst.a;
```

But it isn't.  Rather the result is ending up all mid-tone gray when rendered in headless-gl.  I am not exactly sure how it is ending up in gray.

I believe more than just this one blend mode are incorrect.

I do not need a fix for this as I have worked around this in my code base by writing my own compositing pass that supports various blend modes to avoid relying upon the build-in WebGL blending modes.

/FYI @wvl

**Comment by mikolalysenko** [comment]
Weird, I'll take a look at it.  It might be that one of the constants is getting passed incorrectly.

**Comment by mikolalysenko** [comment]
Can you produce a complete, self-contained example showing the broken behavior?

**Comment by bhouston** [comment]
Great idea!  We have a test case written that fails, we'll submit it today.  :)

There is a second bug in headless-gl we are seeing, but we haven't tracked it down yet to a likely cause...

**Comment by dphil** [comment]
Hi guys!  I'm helping @bhouston out here with the blending mode test that we found to fail.  The PR with that test is here #63

**Comment by mikolalysenko** [comment]
Ok, fixed it.  There was a problem with the validation for constant blend modes being a bit too overzealous.
