### ISSUE TITLE
symbol lookup error on nVidia

### ISSUE THREAD

**Issue by bryanlarsen** [stackgl/headless-gl#65]
node-gl was working fine for me inside Vagrant, then I tried speeding it up by using it on a machine with a real X server on an nVidia card and I got this error:

node: symbol lookup error: .../node_modules/gl/build/Release/webgl.node: undefined symbol: _Z15XextFindDisplayP15_XExtensionInfoP9_XDisplay

I fixed the error by recompiling everything and manually copying webgl.node into my installation.

**Comment by mikolalysenko** [comment]
Seems like a problem with the prebuilt binaries linking statically against some X server configuration.  Maybe the right solution would be to have the prebuild check if the module fails to load and in such an event rebuild the module from source.

@ralphtheninja do you know if there is a way to configure prebuild to do something like this?

**Comment by RaduMilici** [comment]
Hello! I think I'm having the exact same problem with headless-gl, but I'm a bit of a beginner and I'm not quite sure I understand you fix. 

Can you please detail a bit what you did to make it work, I would appreciate it greatly. Thank you for reading. :)

**Comment by NHQ** [comment]
me too, detailed plz

**Comment by ralphtheninja** [comment]
@mikolalysenko Might be hard to check this, since it might load on the machine building the binaries but not on another machine.

You could use https://github.com/juliangruber/require-rebuild to have it be rebuilt on the target machine if the require fails

**Comment by NHQ** [comment]
require-rebuild didn't work for me, but it's a pretty rad hack!

**Comment by tehbelinda** [comment]
Here's what worked for me

1. Set up the system dependencies `sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev` (That was for Ubuntu, see https://github.com/stackgl/headless-gl#system-dependencies)
1. Set up the dev environment, i.e. follow steps 1-6 of https://github.com/stackgl/headless-gl#how-should-i-set-up-a-development-environment-for-headless-gl (Note for step 6 I had to do `npm run rebuild` instead of npm run build)
1. Copy the built webgl.node file into your node module, e.g. `cp headless-gl/build/Release/webgl.node node_modules/gl/build/Release/webgl.node`

**Comment by nina124** [comment]
hi, @tehbelinda 
I followed your instruction, however got stuck in the step 3: `cp headless-gl/build/Release/webgl.node node_modules/gl/build/Release/webgl.node`
I did not find the folder `node_modules/gl/build/Release/webgl.node` under the minos root. And I also checked no node_modules folder in the src code.
Do you created it or is it under other path?

**Comment by tehbelinda** [comment]
Hi @nina124 this would be where ever you ran `npm install` to set up the node modules originally. I'm guessing you are here from the 2 issues linked above, so looking at those, it seems like the part that's run in node is in the `minos/server` path so try looking in there? If not, then you might want to try checking with minos if there's something wrong with the npm setup

**Comment by nina124** [comment]
Thanks @tehbelinda 
Problem solved!

**Comment by dhritzkiv** [comment]
Closing as part of clean up. Feel free to re-open this issue.

**Comment by Karang** [comment]
I had the same issue, and solved it using `npm rebuild --build-from-source gl`

**Comment by trusktr** [comment]
An alternative is the `webgl-raub` package, which worked out of the box without `--build-from-source` for me.

**Comment by entrptaher** [comment]
I solved this with this package.json example.

```json
{
  "name": "video-generation",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "editly": "^0.14.2"
  },
  "overrides": {
    "editly": {
      "gl": "https://github.com/stackgl/headless-gl.git"
    }
  }
}
```

And then,

```
cd node_modules/gl && yarn rebuild
```

It was not working for me otherwise.
