### ISSUE TITLE
texImage2D is more aggressive in checking data size that ANGLE

### ISSUE THREAD

**Issue by bhouston** [stackgl/headless-gl#69]
We are submitting a patch to the ThreeJS project here because headless-gl is more strict in validating the size of data arrays to texImage2D:

https://github.com/mrdoob/three.js/pull/9107

The basic issue is that this check here catches that the size of the data passed in ws 3 bytes when the pack alignment was 4:

https://github.com/stackgl/headless-gl/blob/e68bec8629226590f298cec3aaef4e42d93a22d4/webgl.js#L3548

I am unsure if this is the correct check or if ANGLE's less stringent checking (which I believe is no checking) is the correct approach.

**Comment by dhritzkiv** [comment]
Closing as part of clean up. Feel free to re-open this issue.
