### ISSUE TITLE
gl.clear() failing for framebuffer with RGB color attachment

### ISSUE THREAD

**Issue by dphil** [stackgl/headless-gl#70]
I've created a minimal example in the attached file to demonstrate:

[clear_rgb_buffer.txt](https://github.com/stackgl/headless-gl/files/309754/clear_rgb_buffer.txt)

It fails with INVALID_FRAMEBUFFER_OPERATION, but changing the texture format to RGBA produces no error.

We (@bhouston) have code that functions normally when rendering to, say, the browser, but fails with headless-gl for this reason.

The code that ultimately results in the error is:

```
    if (colorAttachment._format !== gl.RGBA ||
        colorAttachment._type !== gl.UNSIGNED_BYTE) {
      return gl.FRAMEBUFFER_INCOMPLETE_ATTACHMENT
    }
```

in preCheckFramebufferStatus() which runs right before a clear operation. I believe this check can safely be relaxed to allow RGB-formatted color attachments through?

**Comment by mikolalysenko** [comment]
headless-gl doesn't support RGB framebuffer attachments yet.  RGB like ALPHA and LUMINANCE_ALPHA color buffers isn't mandated to be implemented by the spec, and I've had some problems supporting them in older OpenGL environments like the parallels linux driver.

Probably the right thing to do is to emulate the RGB mode for these environments using an RGBA attachment using colorMask, though this would make things more complicated.

**Comment by bhouston** [comment]
(0) Thanks for your attention Mykola!  Interesting that you were working in Parallels, it is only OpenGL 2.1 with no extensions I believe -- that must be hard to work in.  I'd even suggest dropping support for it as I think it is lagging OpenGL ES 2.0 with extensions, and probably very much lagging WebGL 3.0. :)

(1) For non-supported formats the correct return error code is "FRAMEBUFFER_UNSUPPORTED" I believe.

(2) But strangely, I think that headless-gl is the only WebGL implementation I've run into that doesn't support RGB render targets. 

(3) The original framebuffer spec for OpenGL ES 1.0 seems to specify that GL_RGB as a format is a minimum requirement.  My understanding is that OpenGL ES 2.0 included this as base capability:

https://www.khronos.org/registry/gles/extensions/OES/OES_framebuffer_object.txt

(4) The OpenGL desktop extension here includes a number of examples that include creating textures with GL_RGB.  It also includes language such as:

"note that the unsinged base internal formats of RGB, RGBA,
          DEPTH_COMPONENT, and STENCIL_INDEX are legal internal formats
          for renderbuffers.  They were intended to be legal all along
          but the language indicated otherwise."

https://www.opengl.org/registry/specs/ARB/framebuffer_object.txt

**Comment by bhouston** [comment]
I've brought this up on the ThreeJS project here, trying to get the fully correct solution to complete ThreeJS-headless-gl compatiblity: https://github.com/mrdoob/three.js/issues/9122

**Comment by dhritzkiv** [comment]
Closing as part of clean up. Feel free to re-open this issue.
