### ISSUE TITLE
Package fails to install in some environments

### ISSUE THREAD

**Issue by OliveAwesomesauz** [stackgl/headless-gl#71]
headless-gl will fail to install in some environments. My company's build servers do not have GPUs and probably lack important opengl/x11/graphics packages.  The error message is as follows:

```
prebuild WARN install libX11.so.6: cannot open shared object file: No such file or directory
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
```

Is it possible to provide a sane no-op fallback (such as loading nogl when these packages or object files are not available) so the build can succeed?

**Comment by gaving** [comment]
Related: https://github.com/yarnpkg/yarn/issues/1987

**Comment by iambumblehead** [comment]
I see this same error on my laptop a dell XPS13, building the latest gl 4.0.4

**Comment by zheoreh** [comment]
```
prebuild-install WARN install /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /app/node_modules/gl/build/Release/webgl.node)
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.111+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/gl
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

About a week ago I didn't have this problem.

**Comment by zheoreh** [comment]
```
RUN \
  apt-get update -y && \
  apt-get install xserver-xorg-dev libxi-dev libxext-dev -y && \
...
```

It works

**Comment by dhritzkiv** [comment]
Closing as part of clean up. Feel free to re-open this issue.

**Comment by xeoshow** [comment]
> ```
> RUN \
>   apt-get update -y && \
>   apt-get install xserver-xorg-dev libxi-dev libxext-dev -y && \
> ...
> ```
> 
> It works

Hello, 

Could you please tell that how to do this on centOS? Thanks!

**Comment by Jazeb** [comment]
> ```
> RUN \
>   apt-get update -y && \
>   apt-get install xserver-xorg-dev libxi-dev libxext-dev -y && \
> ...
> ```
> 
> It works

Thanks bro you saved my many hours, i have beed looking for solution for the last 3 days. Thanks alot

**Comment by BrennerSpear** [comment]
Still getting this error when I deploy to Vercel / AWS.

Any solution?

**Comment by SunXinFei** [comment]
> How to do on CentOS 7

no resolve, i change Ubuntu , it is well

**Comment by BenceBakos** [comment]
```
sudo apt install libxt-dev
sudo apt install libxi-dev
sudo apt install libgl-dev
```

**Comment by masonbrothers** [comment]
For anyone working with CentOS, this seemed to work for me:
```bash
yum install xorg-x11-server-devel libXi-devel libXext-devel -y
```

@xeoshow  @SunXinFei

**Comment by nonki72** [comment]
> ```
> sudo apt install libxt-dev
> sudo apt install libxi-dev
> sudo apt install libgl-dev
> ```
> 
> Guess someone will find these usefull. https://askubuntu.com/questions/1339727/installing-ffmpg-concat-on-ubuntu-20-04

Thank you this worked on chromebook (ubuntu i believe).
