### ISSUE TITLE
Clean up after build

### ISSUE THREAD

**Issue by mourner** [stackgl/headless-gl#83]
After you install `gl` with NPM and it's built, it leaves 100+ MB of files that are no longer needed (e.g. all the *.o files) but still take all the space. Can we add a cleanup phase in the build script that removes everything that's not necessary? cc @mikolalysenko

**Comment by jfirebaugh** [comment]
`npm install gl` with node v6.8.1 and npm 3.10.8 produces a 268 MB node_modules folder.

* 259 MB is gl itself
  * 205 MB is gl/build
  * 35 MB is gl/prebuilds, which includes tarballs of every combination of gl version and node version
  * 12.4 MB is gl/angle
  * 6.8 MB is gl/deps

Can we slim this down?

**Comment by mourner** [comment]
Should be down to around ~25MB after https://github.com/stackgl/headless-gl/pull/112. Running the prebuilds for new patch release now.
