### ISSUE TITLE
Caching Issue with Yarn

### ISSUE THREAD

**Issue by jas99** [stackgl/headless-gl#92]
After add gl to my node project with
`yarn add gl`

anytime I add/remove new module with yarn; the entire gl project gets rebuild. Is thr way to cache the native builds

Thx

**Comment by nrako** [comment]
This is due to an issue with prebuild which actually [was resolved](https://github.com/mafintosh/prebuild/pull/151) and released in prebuild@5.0.3, but this package still use `^4.1.2`.

**Comment by jas99** [comment]
@nrako Thx buddy for pointing out

**Comment by jas99** [comment]
Hey @mikolalysenko 
Just wanted to bring this to ur attention.

Thx

**Comment by mourner** [comment]
Should be fixed with #94.
