### ISSUE TITLE
webgl.WebGLRenderingContext returns null

### ISSUE THREAD

**Issue by timseverien** [stackgl/headless-gl#95]
I’ve been trying to render stuff using `headless-gl`, but it kept returning null. Apparently, `new webgl.WebGLRenderingContext(...)` in `node_index.js` always returns null, and doesn’t throw an exception.

OS: macOS Sierra 10.12.1

Related libraries:
- XQuartz 2.7.11 (xorg-server 1.18.4)

I used to run an older version of Quartz (can’t remember which), but updating and running `npm rebuild` wouldn’t work :(

Am I missing dependencies or anything?

**Comment by gre** [comment]
I wonder why there is any legitimate reason we didn't want this to throw and we just silent the error at the moment..

**Comment by dhritzkiv** [comment]
This should be fixed in the latest Node JS (versions 12 and 13). It was likely a libuv process bug that occurred in certain cases.

**Comment by gre** [comment]
Interesting!
