### ISSUE TITLE
Stencil buffer not cleared with gl.clear

### ISSUE THREAD

**Issue by w0rm** [stackgl/headless-gl#97]
First of all, thanks for working on this library. I'm planning to use it to test [WebGL in Elm](http://package.elm-lang.org/packages/elm-community/webgl/latest) and it looks very promising!

Currently, I'm just trying to render some examples that we have. I had no troubles rendering the simplest [cube example](http://webgl.elm-community.org/examples/cube.html), and then tried to render [the crate example](http://webgl.elm-community.org/examples/crate.html) that uses the stencil test in order to create a mirror effect (the floor is added to the stencil buffer and then the reflection is tested against it). The result looks like the stencil buffer is not properly cleared from the previous frames, however `gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT | gl.STENCIL_BUFFER_BIT);` is certainly called every time before the whole scene is rendered:

![before](https://cloud.githubusercontent.com/assets/43472/21751820/b524e99c-d5cd-11e6-9064-bb135941ed2d.png)

I then tried to manually clear the stencil buffer, and rendered another floor, with the stencil test that always fails with the zero operation, that erases the stencil buffer. This fixed the issue for me:

![after](https://cloud.githubusercontent.com/assets/43472/21751824/bba123ee-d5cd-11e6-98e4-76ecb4e063cb.png)

I'm not sure if the bug belongs here or to the underlining library, or if there is something in my code that is wrong. Would be glad if you point me in the right direction.

**Comment by bdoss** [comment]
I'm not sure if this helps or not, but I felt like I was facing a similar struggle as you on this. What I found worked for me was creating the headless-gl context as such:
```
gl(width, height, { stencil: true });
```
It seems as though stencil is disabled by default:

https://github.com/stackgl/headless-gl/blob/5763725b1ad47b4a56254e4ee994c3483effb6ac/node_index.js#L26

**Comment by w0rm** [comment]
@bdoss I am enabling the stencil, but I cannot clear the stencil buffer with `gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT | gl.STENCIL_BUFFER_BIT);`

**Comment by bdoss** [comment]
Gotcha. Maybe my comment will be helpful for someone in the future that comes across this issue searching for stencil problems related to headless-gl. :)

**Comment by w0rm** [comment]
I figured this. The bug was caused by not resetting the stencil mask correctly.
